### ISSUE TITLE
Read URL Entity parameters 

### ISSUE THREAD

**Issue by engharb** [s9e/TextFormatter#102]
Hello,

I want to read the {TEXT} of [URL]{TEXT}[/URL], in order to validate its value/domain. Is that possible? and Could you give me an example?

Thank you,

**Comment by engharb** [comment]
@JoshyPHP 
I have tried that before and I used to get "Filter 'myfilter' is neither callable nor an instance of s9e\TextFormatter\Configurator\Items\AttributeFilter"

**Comment by JoshyPHP** [comment]
You need to provide a *callable* callback. See http://php.net/manual/en/language.types.callable.php

In the example I provided, `myfilter` is defined at the top.

**Comment by engharb** [comment]
@JoshyPHP 
thanks  a lot. I have found a solution for my case based on your response as the following:
```
$configurator->BBCodes->addCustom(
            '[url url={URL;useContent} string={REGEXP=/^\w/;useContent}]{TEXT}[/url]',
            '<a href="{URL}" rel="{@string}">{TEXT}</a>'
        );
    $configurator->tags['url']->attributes['string']->filterChain->append('Ebesucher\\ForumHelperClass::customizedUrlFilter');
```
