### ISSUE TITLE
Add FONT cutomer filter

### ISSUE THREAD

**Issue by engharb** [s9e/TextFormatter#104]
Hi,

I have the following example 
```
[FONT=&amp]abcdefg[/FONT] // &amp must be escaped by API
```
I tried to filter that when the expression of FONT is a non-char then set the family-font as arial as the following: 
```
public static function customizedFontlFilter($fontname)
    {
        if (preg_match('/^(\W)/', $fontname)) {
            return "arial";
        }

        return $fontname;

    }

$configurator->BBCodes->addCustom(
                '[font font={REGEXP=/^(\W|\w)/}]{TEXT}[/font]',
                '<span style="font-family:{@fontname}">{TEXT}</span>
'
            );
$configurator->tags['FONT']->attributes['fontname']->filterChain->append('Ebesucher\\ForumHelperClass::customizedFontlFilter');
```

I used to get:
```
"Attribute 'fontname' is not properly sanitized to be used in this context"

&lt;span <span style="background-color:#ff0">style=&quot;font-family:{@fontname}&quot;</span>&gt;\n
  &lt;xsl:apply-templates/&gt;\n
&lt;/span&gt;
```

Any idea how to filter the name of family font correctly?

**Comment by JoshyPHP** [comment]
There are two issues:

 1. You named the attribute `font=` in the definition, it should be `fontname=`.
 2. The regexp `/^(\W|\w)/` means "anything that starts with not a word character, or a word character", which effectively means "anything." Also, if the regexp is not anchored at the end, the filter cannot prevent from abuse, e.g. `x;color:red;font-size:200px`

There's already a [built-in filter](https://s9etextformatter.readthedocs.io/Filters/Built-in_filters/) that can be used to validate font-family names: `[FONT fontname={FONTFAMILY}]`

**Comment by engharb** [comment]
I have the same context used for URL and it was working. I did not find any clear answer in your response, Also the API does not render the BBCode content correctly especially closing the tags.

**Comment by JoshyPHP** [comment]
```php
$configurator->BBCodes->addCustom(
	'[font fontname={FONTFAMILY}]{TEXT}[/font]',
	'<span style="font-family:{@fontname}">{TEXT}</span>'
);
```

**Comment by engharb** [comment]
Thanks, I have tried that correctly before, but I want to filter invalid fontname if it is i.e (& or %) or something else then set the family-font as i.e Arial, else keep it as it is.

The filter i.e:
$configurator->tags['FONT']->attributes['fontname']->filterChain->append('Ebesucher\\ForumHelperClass::customizedFontlFilter');

**Comment by JoshyPHP** [comment]
If you want a default value, you can add it in the definition:
```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addCustom(
	'[font fontname={FONTFAMILY;defaultValue=Arial}]{TEXT}[/font]',
	'<span style="font-family:{@fontname}">{TEXT}</span>'
);

extract($configurator->finalize());

$text = '[FONT=&amp]abcdefg[/FONT]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<span style="font-family:Arial">abcdefg</span>
```
