### ISSUE TITLE
Bug: Formatter does not render correctly

### ISSUE THREAD

**Issue by engharb** [s9e/TextFormatter#105]
I have the following formatter configuration
```
$configurator->BBCodes->addCustom(
            '[FONT fontname={FONTFAMILY;defaultValue=inherit}]{TEXT}[/FONT]',
            '<span style="font-family:{@fontname}">{TEXT}</span>'
        );
```

And an example
```
[COLOR=#333333][FONT=*][LEFT] 

[TABLE]
[TR]
[TD][SIZE=3]Über [B]1930731 Benutzer[/B] Testing Formatter [/SIZE][/TD]
[/TR]
[/TABLE]

[/LEFT][/FONT][/COLOR]
```

The result after parsing to html:
```
... the table here ...
[/FONT][/COLOR] 
```

The font and color tags are not closed.

And when I change configuration to:
```
$configurator->BBCodes->addCustom(
            '[FONT fontname={FONTFAMILY;defaultValue=inherit}]{TEXT}[/FONT]',
            '<div style="font-family:{@fontname}">{TEXT}</div>'
        );
``` 

I used to get correct parsed html code.

**Comment by JoshyPHP** [comment]
Not a bug, just the application of [Automatic rules generation](https://s9etextformatter.readthedocs.io/Rules/Automatic_rules_generation/). `span` elements cannot contain `table` elements so the library automatically closes the `FONT` tag. Without a start tag, the closing tags are ignored and appear as text.

**Comment by engharb** [comment]
thanks a lot.
