### ISSUE TITLE
List of the custom sites added

### ISSUE THREAD

**Issue by rxu** [s9e/TextFormatter#106]
More a question rather than an issue, but is there a way to iterate through the custom site definitions added just like you do for the cached default definitions via the ```$configurator->MediaEmbed->defaultSites``` object?

**Comment by JoshyPHP** [comment]
Ok, that makes sense. It would have to be read-only because changing the configuration after a site has been added would not have the desired effect.

I'll add something in 1.3.0.

**Comment by rxu** [comment]
Thanks.
