### ISSUE TITLE
XKCD support

### ISSUE THREAD

**Issue by tankerkiller125** [s9e/TextFormatter#107]
It would be really awesome if this library added XKCD support so that we could link XKCD and it would automatically display the image and the text of the comics. XKCD does have an API https://xkcd.com/json.html

**Comment by JoshyPHP** [comment]
I won't add it to the MediaEmbed plugin because I don't think replacing XKCD links is a behaviour an average user would expect but you can add it for yourself as a custom site. For example:

```php
$configurator = new s9e\TextFormatter\Configurator;

$tag = $configurator->MediaEmbed->add(
	'xkcd',
	[
		'host'   => 'xkcd.com',
		'scrape' => [
			'url'     => 'https://xkcd.com/{@id}/info.0.json',
			'match'   => '#xkcd\\.com/(?<id>\\d+)#',
			'extract' => [
				'#"num":\\s*(?<id>\\d+)#',
				'#"img":\\s*"(?<img>[/.:\\w]+)"#',
			]
		]
	]
);
$tag->attributes['img']->filterChain->append('#url');
$tag->template = '<a href="https://www.xkcd.com/{@id}/"><img src="{@img}"></a>';

extract($configurator->finalize());

$text = 'https://www.xkcd.com/2074/';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<a href="https://www.xkcd.com/2074/"><img src="https://imgs.xkcd.com/comics/airplanes_and_spaceships.png"></a>
```

https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/

**Comment by franzliedke** [comment]
This library is amazing! :heart: 

The amount of times that feature request issues where closed with a "This is already easily possible" and a five-line code snippet speaks volumes.

Hats off!
