### ISSUE TITLE
gist links

### ISSUE THREAD

**Issue by johnd0e** [s9e/TextFormatter#114]
1. At the bottom of included gist there is info-bar from GitHub
```
sample.js hosted with ❤ by GitHub                                                  view raw
```
`sample.js` and `view raw` are actually github links.
These links can be opened, but only in new window, and they fail to open if we just click on them.

2. Every gist can contain several files.
I want to be able to include only 1 specified file.
Is it possible to implement such feature?

---
(I was told that this library is used in phpbb, so I write here. Please point me if mentioned features are out of scope of TextFormatter)

**Comment by JoshyPHP** [comment]
1. The content is hosted by GitHub, neither of us control how those links behave. That could be a bug in GitHub's code, although I can't say for sure without seeing the original embed.
2. I don't know. If you post the Gist's URL I'll look into it.

**Comment by johnd0e** [comment]
1. Sample: https://forum.farmanager.com/viewtopic.php?p=146934#p146934
2. Sample: https://gist.github.com/laustdeleuran/1948627

**Comment by JoshyPHP** [comment]
I looked into the issue with links and it's not a bug, it's just that those embeds are hosted in an iframe so left-clicking on links won't have the same effect as clicking another link on the page. Anyway, I have [modified the host iframe so that links open in the top context](https://github.com/s9e/s9e.github.io/commit/95402be4200f60f211ea6250abfcc715af67032f). The update is immediate if you clear your browser's page.

It's technically possible to embed a specific file from a Gist but how would a user specify which file? There's a canonical link for the raw file but I'm not sure that's something that people really use.

**Comment by johnd0e** [comment]
>  but how would a user specify which file?

Personally I would be happy with any way.
But in general it's more convenient to use github-provided permalinks as they are visible right at the main gist page.

**Comment by JoshyPHP** [comment]
The issue with those permalinks is that they don't contain the file's name, only a variation of it.

The raw links do contain the file's name but they are not currently supported and adding support for them is more trouble than they're worth I'm afraid.

**Comment by johnd0e** [comment]
> a canonical link for the raw file but I'm not sure that's something that people really use.

Actually the links themselves present in resulting embed, so it' not an issue

> The raw links do contain the file's name but they are not currently supported

Well, raw links are supported now, so I could easily embed link like this:
https://gist.github.com/laustdeleuran/1948627/raw/1cb2f8d2eb74a8f81b5985d86d53282e687639a8/one.js
Unfortunately the whole gist is rendered now in this case

>  adding support for them is more trouble than they're worth I'm afraid.

Please still consider the possibility to support separate files, may be in future.

**Comment by johnd0e** [comment]
Just for reference, I found such possibilities:
* A simple as:
```
<script src="https://gist.github.com/laustdeleuran/1948627.js?file=two.js"></script>
```
* It's even possible to embed only certain lines from gits with this library https://github.com/blairvanderhoof/gist-embed
* another great possibility is to embed github file using this: http://gist-it.appspot.com/
  (It actually deserves separate issue)

**Comment by JoshyPHP** [comment]
I may consider adding support for individual in the future if GitHub adds a form of permalinks that can be used easily but in the meantime it would require more effort than it's worth I'm afraid. Note that raw links are not really supported and will not necessarily link to the correct revision.

Of course, it's always possible to edit tags via the PHP API, or add your own media sites via this API: https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/
