### ISSUE TITLE
Censor cannot handle multiple words

### ISSUE THREAD

**Issue by woganmay** [s9e/TextFormatter#115]
I'm trying to use this plugin within Flarum. If I set it up to censor one word, it works fine:

    return [
        (new Extend\Formatter)
            ->configure(function (Configurator $config) {
                $config->Censor->add('nuggets'); // this works
                $config->Censor->add('redapples'); // Adding this breaks it
            })
    ];

The moment I add a second word, the parser decides that the group is invalid:

    Uncaught SyntaxError: Invalid regular expression: /(?:^|\W)(?>nugget|redapple)s(?!\w)/: Invalid group

I've followed the code all the way through to the NormalizedCollection trait and can't find anything wrong on the PHP side. Any ideas? I'm running `Flarum core 0.1.0-beta.8.1` .

**Comment by JoshyPHP** [comment]
I don't know where that exception originates from but I think it might be related to atomic grouping in JavaScript. Try applying the change from this commit to your local install, hopefully it will fix it. If it doesn't, post the full backtrace for that exception, it may contain useful information.

**Comment by woganmay** [comment]
Lifesaver! The commit worked as expected. If you had a donate button I'd send you a few coffees :)

**Comment by JoshyPHP** [comment]
Glad it worked. The commit is in version 1.4.2 released the other day.

I have a donate button for my XenForo stuff but I never thought about having it on the library's page. Thanks for the suggestion, I'll think about it.


[![](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG_global.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6P6985GT2DLGL) [![](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG_global.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ABGFV5AGE98AG)
