### ISSUE TITLE
Amazon media embed not working (removes parameters)

### ISSUE THREAD

**Issue by rookey** [s9e/TextFormatter#116]
Hello,

it seems that since a few months, the a9a/mediaembed plugin isn't working for Amazon links anymore.

Example link: https://www.amazon.de/Neue-Antidepressiva-atypische-Neuroleptika-Niedrigdosierung/dp/3925931686/ref=as_li_ss_tl?ie=UTF8&linkCode=ll1&tag=rlf&linkId=52cca62ff5aea79f228a5e519566bb5e&language=de_DE

The preview image of Amazon displays fine, it also contains the link - only the "&tag=rlf" parameter is truncated to an empty one ("&tag=").

Is there any way to preserve the &tag= parameter if one is already there?

**Comment by JoshyPHP** [comment]
The plugin works as intended. The Amazon associate tag of the original link is ignored and only the Amazon associate tags set during configuration are used. The template parameter `AMAZON_ASSOCIATE_TAG_DE` can be used to set an Amazon associate tag for their .de site.

* https://s9etextformatter.readthedocs.io/Templating/Template_parameters/
* https://github.com/s9e/TextFormatter/blob/c62c1b3a5e595bf45557aa1190cb14666c621cce/src/Plugins/MediaEmbed/Configurator/sites/amazon.xml#L15-L25
