### ISSUE TITLE
gfycat is not loading (cross-origin or sameorigin error)

### ISSUE THREAD

**Issue by czuczuczu** [s9e/TextFormatter#118]
Hi, i think there might be a problem with gfycat. I am using latest release **1.4.3 (2019-04-26)**

In DevTools console I have this error:

- on firefox
`Load denied by X-Frame-Options: [url_to_gfycat_resource_here] does not permit cross-origin framing.`

- on chrome
`Refused to display '[url_to_gfycat_resource_here]' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

And on website it looks like this (chrome screenshot):
https://i.imgur.com/iOC7FUR.png

Is there anything I can do to resolve this problem?

**Comment by JoshyPHP** [comment]
Gfycat works fine for me locally. Make sure the URL for the Gfycat iframe starts with `//gfycat.com/ifr/` and not `//gfycat.com/iframe/`. If so, it means you're using an older version.

**Comment by czuczuczu** [comment]
Thanks for quick response, @JoshyPHP 
It looks, that you're right with this ifr / iframe. I am using latest release, but it is customized. I will check it and report back.
