### ISSUE TITLE
Amazon not working

### ISSUE THREAD

**Issue by TarantinoMariachi** [s9e/TextFormatter#119]
https://www.amazon.es/Dragon-Ball-Cap-133-138-DVD/dp/B0055KN9BM/

Doesn't seem to work properly. But if I use an URL from amazon.co.uk it works perfectly.

**Comment by JoshyPHP** [comment]
It works fine for me. If you can't see its content, it may be related to an adblocker.

**Comment by TarantinoMariachi** [comment]
I was testing in my phone. So, no adblockers.

This is the result: 
https://i.imgur.com/a/dM2DMSq.png

As you can see the co.uk shows the product but the .es doesn't.
