### ISSUE TITLE
How to get the value of a XPath {@attribute}?

### ISSUE THREAD

**Issue by AlfredoRamos** [s9e/TextFormatter#123]
Hi,

I've created a phpBB extension (3.2.7, TextFormatter 1.4.2) in which the user can specify an `alt` attribute in images.

https://github.com/AlfredoRamos/phpbb-ext-image-alt/blob/26a99a3313c4e587a0f9ae478635e200ec1b0e2a/event/listener.php#L69-L80

Everything works just fine when a value is not specified except when using the Litedown plugin (from another of my extensions). Examples:

<details>
<summary>BBCode</summary>

**Input**
```
[img]https://help.duckduckgo.com/duckduckgo-help-pages/images/fb5a7e58b23313e8c852b2f9ec6a2f6a.png[/img]
[img alt="DuckDuckGo"]https://help.duckduckgo.com/duckduckgo-help-pages/images/fb5a7e58b23313e8c852b2f9ec6a2f6a.png[/img]
```

**Output**
```html
<img src="https://help.duckduckgo.com/duckduckgo-help-pages/images/fb5a7e58b23313e8c852b2f9ec6a2f6a.png" class="postimage" alt="Image"><br>
<img src="https://help.duckduckgo.com/duckduckgo-help-pages/images/fb5a7e58b23313e8c852b2f9ec6a2f6a.png" class="postimage" alt="DuckDuckGo">
```
</details>

<details>
<summary>Markdown (Litedown)</summary>

**Input**
```markdown
![](https://help.duckduckgo.com/duckduckgo-help-pages/images/fb5a7e58b23313e8c852b2f9ec6a2f6a.png)
![DuckDuckGo](https://help.duckduckgo.com/duckduckgo-help-pages/images/fb5a7e58b23313e8c852b2f9ec6a2f6a.png)
```

**Output**
```html
<img src="https://help.duckduckgo.com/duckduckgo-help-pages/images/fb5a7e58b23313e8c852b2f9ec6a2f6a.png" class="postimage" alt=""><br>
<img src="https://help.duckduckgo.com/duckduckgo-help-pages/images/fb5a7e58b23313e8c852b2f9ec6a2f6a.png" class="postimage" alt="DuckDuckGo">
```
</details>

I think it's because in Litedown I'm sending a empty string (`![](url)`) so I would like to know if there's a way to get the value passed by the user (`{@alt}`) in the markup (BBCode/Markdown) after it has been parsed and before it is rendered so I can update the attribute value only if it's not empty, something like:

```php
foreach ($dom->getElementsByTagName('img') as $node)
{
	if (!empty($obj->getValue('{@alt}')))
	{
		$node->setAttribute('alt', '{@alt}');
	}
}
```

I tried using `$node->getAttribute('alt')` but I always get `{$L_IMAGE}` (the configured default value) or the value XPath expression itself `{@alt}`.

I also tried using `DOMXPath`, but the `nodeValue` is always `NULL`

Is there a way to get its value without using DOM after the HTML is generated?

https://github.com/AlfredoRamos/phpbb-ext-image-alt/blob/master/event/listener.php
https://github.com/AlfredoRamos/phpbb-ext-markdown/blob/master/event/listener.php

**Comment by JoshyPHP** [comment]
The Markdown output is correct, in that it's [the markup that most implementation will generate](https://johnmacfarlane.net/babelmark2/?normalize=1&text=!%5B%5D%28https%3A%2F%2Fhelp.duckduckgo.com%2Fduckduckgo-help-pages%2Fimages%2Ffb5a7e58b23313e8c852b2f9ec6a2f6a.png%29). If I understand you, you'd want the Litedown markup to use a default string if the value for the alt attribute was left empty?

You'd have to test it in the template with something like that:
```php
$tag = $configurator->tags['img'];
$tag->template = str_replace(
	'<xsl:copy-of select="@alt"/>',
	'<xsl:attribute name="alt">
		<xsl:choose>
			<xsl:when test="@alt != \'\'"><xsl:value-of select="@alt"/></xsl:when>
			<xsl:otherwise><xsl:value-of select="$L_IMAGE"/></xsl:otherwise>
		</xsl:choose>
	</xsl:attribute>',
	$tag->template
);
```

Ideally you'd [manipulate the template using DOM](https://s9etextformatter.readthedocs.io/Templating/Modify_a_template/#as-a-dom-tree) rather than string functions but you get the point.

**Comment by JoshyPHP** [comment]
Additionally, you can add your own filters to reject empty alt attributes or anything that doesn't contain a non-space, e.g.

```php
$configurator->tags['img']->attributes['alt']->filterChain
	->prepend('#regexp')->setRegexp('/\\S/');
```

**Comment by AlfredoRamos** [comment]
Thanks!

This seems to work perfectly:

```php
$configurator->tags['img']->attributes['alt']->filterChain
	->prepend('#regexp')->setRegexp('/\\S/');
```

I was about to "fix" it by manipulating the HTML with DOM, but your second solution seems to do the job in a more elegant way.

Thanks again.
