### ISSUE TITLE
phpBB: excessive <p> in content block

### ISSUE THREAD

**Issue by johnd0e** [s9e/TextFormatter#128]
I'm not exactly sure that my issue belongs to TextFormatter, or to it's phpBB integration part.

Anyway, when I use [Markdown](https://www.phpbb.com/community/viewtopic.php?t=2514516) extension, I see that content block of forum post is whole wrapped into additional `<p>` tag.

And in my setup it causes problem (conflict with bbcode).

So I want to ask: is it feature of Litedown plugin? Or something wrong in phpBB?

**Comment by JoshyPHP** [comment]
The Litedown plugin automatically turns on paragraphs to remain faithful to the spirit of the original Markdown syntax.

It can be disabled globally by removing the [rules generator](https://s9etextformatter.readthedocs.io/Rules/Rules_generators/):
```php
$configurator->rulesGenerator->remove('ManageParagraphs');
```

I believe you can also disable it locally in your [BBCode definition](https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Custom_BBCode_syntax/#tag-rules):
```
[x #createParagraphs=false]{TEXT}{/x]
```

**Comment by johnd0e** [comment]
Well I've tried to add that parameter, but that didn't help.
```
[spoiler={REGEXP=/.+/;optional;defaultValue=Spoiler} #createParagraphs=false]{TEXT2}[/spoiler]
```

<details>

```html
<span class="spoiler">
<input type="button" Value="{REGEXP}" class="button2" style="font-size:10px; margin: 0px 5px 0px 5px" onclick="
if(this.parentNode.getElementsByTagName('div')[0].style.display!='')
this.parentNode.getElementsByTagName('div')[0].style.display='';
else
this.parentNode.getElementsByTagName('div')[0].style.display='none';

"/>
<div class="spoilercontent" style="margin: 3px 0px 0px 0px; padding: 5px; border-width: 1px; border-style:dotted; display: none;">
{TEXT2}
</div>
</span>
```
</details>

**Comment by JoshyPHP** [comment]
Could be because Litedown already has a spoiler tag. https://s9etextformatter.readthedocs.io/Plugins/Litedown/Syntax/#spoilers

**Comment by johnd0e** [comment]
> Could be because Litedown already has a spoiler tag.

Thank's, that is good to know.
But I think that is completely different thing.

Anyway, let's try from another side:

> ```
> $configurator->rulesGenerator->remove('ManageParagraphs');
> ```

Where can I enter this?

**Comment by JoshyPHP** [comment]
You'd need to create an extension so if your issue is with a BBCode I don't recommend it.

**Comment by johnd0e** [comment]
Ok. So what should I do?

I've tried to rename my bbcode to "spoiler2" but it haven't helped.

**Comment by JoshyPHP** [comment]
You should start at the beginning and describe what you enter in the post, what the output is and what you would like the output to be.

**Comment by johnd0e** [comment]
1. I have custom bbcode for spoiler, and it is working for years without any problem.
   (I've posted it's code above.)
   Sample usage: `[spoiler2="title"]hidden text[/spoiler2]`
2. After I enable Markdown extension - my bbcode stopped to work.
    With chrome dev tools I can see that my bbcode is substituted is some weird way:
   ```html
   <div class="content"><p><span class="spoiler"><input type="button" value="title" class="button2" style="font-size:10px;margin:0 5px 0 5px" onclick=" if(this.parentNode.getElementsByTagName('div')[0].style.display!='') this.parentNode.getElementsByTagName('div')[0].style.display=''; else this.parentNode.getElementsByTagName('div')[0].style.display='none';  "></span></p><div class="spoilercontent" style="margin:3px 0 0 0;padding:5px;border-width:1px;border-style:dotted;display:none">hidden text</div><p></p></div>
   ```

**Comment by johnd0e** [comment]
3. After I disable Markdown extension and post same text again - it begins to work as intended.
   With dev tools I see correct substitution now:
   ```html
   <div class="content"><span class="spoiler"><input type="button" value="title" class="button2" style="font-size:10px;margin:0 5px 0 5px" onclick=" if(this.parentNode.getElementsByTagName('div')[0].style.display!='') this.parentNode.getElementsByTagName('div')[0].style.display=''; else this.parentNode.getElementsByTagName('div')[0].style.display='none';  "><div class="spoilercontent" style="margin: 3px 0px 0px; padding: 5px; border-width: 1px; border-style: dotted; display: none;">hidden text</div></span></div>
   ```

**Comment by JoshyPHP** [comment]
Your HTML is invalid because you can't have a `div` in a `span`. The browser probably fixes the DOM tree and the assumptions you make in your JavaScript become invalid as well because the actual DOM tree doesn't match what you thought it would be. That's my guess.

Replace your HTML with the `details` element or install a spoiler extension for phpBB and it should work better.

**Comment by johnd0e** [comment]
May be this code does not follow specs, but every known browser is happy with such html. Our board uses it for years. 

The problem arises ONLY after I enable Markdown extension. 

When Markdown enabled expansion of my bbcode become garbled. It is extremely invalid, try to make replacements by hands and you will see.

Sorry that I've pasted that html unformatted, that's how it's copied from browser. Tomorrow I will reformat it to makes issue more clearly visible.

**Comment by johnd0e** [comment]
P. S. 
Replace that bbcode with something modern is good idea, but it is not easy at the moment, as I have to convince our board administrators, find better bbcode, and make sure that it is compatible with thousands of already existent posts.

I am going to do it anyway, but still, I believe that some bug is hidden in Markdown extension, and better to fix it's lowest level cause.

**Comment by johnd0e** [comment]
> You'd need to create an extension so if your issue is with a BBCode I don't recommend it.

Could you point me to skeleton of some most primitive extension without any UI?
Just to add that line of code and check if it helps.

**Comment by JoshyPHP** [comment]
> May be this code does not follow specs, but every known browser is happy with such html.

Browsers handle bad markup just fine because the way to handle misnested tags is in the specs too: https://www.w3.org/TR/html53/syntax.html#an-introduction-to-error-handling-and-strange-cases-in-the-parser -- You'll notice that they fix the markup by creating new nodes and/or moving them around.

I don't use spoiler extensions so I don't know whether any of them have any UI. You can try this one, it seems popular: https://www.phpbb.com/customise/db/extension/simple_spoiler_bbcode/

**Comment by johnd0e** [comment]
It seems that you've misunderstood my question. I asked how should I apply your advice about removing rule 'ManageParagraphs'.

You answrted that I need to write extension to use that.
But I have no idea how to compose phpBB extension, that's why I asked your about some sample.

**Comment by JoshyPHP** [comment]
You need to use phpBB's documentation in order to learn how to create a phpBB extension. https://area51.phpbb.com/docs/dev/3.2.x/extensions/tutorial_bbcodes.html

**Comment by johnd0e** [comment]
Ok, many thanks for your patience.
Now things are more clear for me.

I have last question: why [createParagraphs](https://s9etextformatter.readthedocs.io/Rules/Tag_rules/#createParagraphs) tag [rule](https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Custom_BBCode_syntax/#tag-rules) does not work for [my tag](https://github.com/s9e/TextFormatter/issues/128#issuecomment-580792337)?

Is it a bug in TextFormatter?
If not then could you explain how it is supposed to act?
I see no difference in resulting html.

**Comment by JoshyPHP** [comment]
The `createParagraphs` rule works as intended and no paragraph is created inside of the spoiler. You can verify that by looking at the page's source: (not "Inspect element")
```html
<p><span class="spoiler"><input type="button" value="title" class="button2" style="font-size:10px;margin:0 5px 0 5px" onclick=" if(this.parentNode.getElementsByTagName('div')[0].style.display!='') this.parentNode.getElementsByTagName('div')[0].style.display=''; else this.parentNode.getElementsByTagName('div')[0].style.display='none';  "><div class="spoilercontent" style="margin:3px 0 0 0;padding:5px;border-width:1px;border-style:dotted;display:none">text</div></span></p>
```
The reason you see a different DOM tree when inspecting the element is because the markup is invalid and this is the way browsers must handle invalid markup as per HTML 5. `span` does not allow `div` so the `div` is [moved to the parent](https://www.w3.org/TR/html53/syntax.html#adoption-agency-algorithm), but `p` doesn't allow it either and it is moved up further. I don't know off the top of my head why an empty paragraph is created but since Chrome and Firefox behave the same way I assume it's as per the HTML 5 specs.

If you replace the `span` with a `div` it should fix your markup.

**Comment by johnd0e** [comment]
Thank you for insight, but after your post I've made my own investigation, and cannot completely agree to you.

Replacing `div` by `span` indeed fixes the issue. But does it mean that that was root cause of it? I doubt. When I put `<span><div></div></span>` into `span_div.html` and inspect it in Chrome dev tools - I see perfectly correct DOM, identical to that I put into file.

What is real problem - wrapping all that content into `<p>`:
`<p><span><div></div></span></p>` - this leads to `<body><p><span></span></p><div></div><p></p></body>`.
Indeed, this is expected, as [`<p>` docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) explicitly state: Permitted content: [Phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content).
And exact root cause of difference between our html and rendered DOM is **Tag omission** (described in the same article).

Thus, in my opinion, the most proper fix for the issue: **check if markup contains any block-level element, and if it does - do not wrap it into `<p>`**

**Comment by johnd0e** [comment]
The issue indeed can be workarounded replacing `div` with `span`, but this works only for that particular case.

Consider another (real) sample: I want to implement spoiler using `<details>` tag.
But I want to make it inline.
Is it possible? Definitly: https://codepen.io/johnd0e-the-bashful/pen/eYmOmBQ
Is it against any spec? No.

So I want to make bbcode for it.
Unfortunately, TextFormatter will wrap it all `<p>` , and brake my intention.

**Comment by JoshyPHP** [comment]
There already is a [rule generator](https://s9etextformatter.readthedocs.io/Rules/Rules_generators/) that manages paragraphs named `ManageParagraphs`. If the root element of a template is inline, then the whole template is considered inline and it's output inside of a paragraph. If the root element is a block, it will generally be output outside of a paragraph.

[The details element](https://www.w3.org/TR/html53/interactive-elements.html#the-details-element) is a "flow content" element. It's not used for phrasing and will close paragraphs. If you want to create inline spoilers, you'd have to use something like a `span`.

**Comment by johnd0e** [comment]
> [The details element](https://www.w3.org/TR/html53/interactive-elements.html#the-details-element) is a "flow content" element.

Flow content is not something specific. Span is also flow content element.


> If you want to create inline spoilers

But my inline spoiler contain block element, by intention.
It is hidden most of the time, that's why it is good to have it inline.
But when expanded - spoiler button stays inline, but content appear in block element.

I am trying to draw you attention to this:
- block element inside of inline element - valid construction, which can be effectively used. This is not against any spec.
- TextFormatter currently do not support this (well, rather rare) case.
- This may be improved.
  Well, you already explained how to _workaround_ my cases, thanks.
  But may be that can be really improved on TextFormatter side?

**Comment by JoshyPHP** [comment]
Most (if not all) phrasing content elements are also flow content element. That's why elements that allow flow content elements don't list phrasing content elements in their content model. Similarly, `span` is said to be used "Where phrasing content is expected." without having to also mention it can be used where flow content is expected. The crucial point is that `div` is not a phrasing content element and `span` only allows phrasing content elements. If you're unsure whether something is valid, you can use the [W3C validator online](https://validator.w3.org/#validate_by_input).

I don't want to try to outsmart the library's users. Some rules are generated based on the HTML 5 specs but whenever something is unclear, invalid or particularly difficult to implement, I prefer to leave the decision to the user. In your case, the template could be automatically modified to be made valid by moving the `div` out of the `span`. With that modification, spoilers would automatically close paragraphs via a [breakParagraph](https://s9etextformatter.readthedocs.io/Rules/Tag_rules/#breakParagraph) rule. The issue with that approach is that it requires the library to closely follow the latest HTML specs and any deviation could have unexpected consequences. That's why if something is invalid I let users decide how to handle it. If you want to use `div` in a `span` the library won't stop you. If you think your spoiler should close paragraphs, you can use a `breakParagraph` rule.

**Comment by johnd0e** [comment]
> In your case, the template could be automatically modified to be made valid by moving the `div` out of the `span`.

Unfortunately not, as I'm trying to achieve exactly this:
- spoiler button as inline element
- content (when unhidden) as block element

Our forum uses exactly this setup for a long time. May be even since IE5, so it is not something 'modern'.

> The issue with that approach is that it requires the library to closely follow the latest HTML specs and any deviation could have unexpected consequences.

Well, I see 2 possible approaches:
- Either library should detect such cases.
  Currently (as you wrote): _If the **root element** is a block, it will generally be output outside of a paragraph._
  Better: Inspect **descendants** too, and if any block element found then avoid paragraphs.
- Or do not to try be smart, but introduce some new tag rule, that could be specified for my bbcode explicitly.

> If you think your spoiler should close paragraphs, you can use a `breakParagraph` rule.

But I do not want to break paragraph, I really want my bbcode inline

**Comment by johnd0e** [comment]
> If you're unsure whether something is valid, you can use the [W3C validator online](https://validator.w3.org/#validate_by_input).

Validators are not perfect too.
Consider TextFormatter default spoiler:
```
<details>hidden text</details>
```
This validator states: **Error: Element details is missing a required instance of child element summary.**
But in [spec](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element) I see:
> The first summary element child of the element, **if any**, represents the summary or legend of the details. **If there is no child summary element**, the user agent should provide its own legend (e.g. "Details").

**Comment by JoshyPHP** [comment]
Just use CSS and make a span appear like a block element.

**Comment by johnd0e** [comment]
Thank you for wonderful library and great support!

> It can be disabled globally by removing the [rules generator](https://s9etextformatter.readthedocs.io/Rules/Rules_generators/):
> 
> ```
> $configurator->rulesGenerator->remove('ManageParagraphs');
> ```

I've managed this by creating primitive phpBB extension using [this tool](https://www.phpbb.com/customise/db/official_tool/ext_skeleton/) (with only enabled `PHP event listeners` component).
<details>

I've changed single source file `main_listener.php`:
```php
	public static function getSubscribedEvents()
	{
		return array(
			'core.user_setup'				=> 'load_language_on_setup',
			'core.display_forums_modify_template_vars'	=> 'display_forums_modify_template_vars',
			'core.text_formatter_s9e_configure_after'	=> array('configure_plugins',-1),
		);
	}
```
```php
	public function configure_plugins($event)
	{
		$configurator = $event['configurator'];
		$configurator->rulesGenerator->remove('ManageParagraphs');
		extract($configurator->finalize());
		$event['configurator'] = $configurator;
	}
```
</details>

BTW, what is recommended way to check whether some plugin is loaded or not?
And whether some rules generator is added or not?

**Comment by JoshyPHP** [comment]
Glad you like it.

You don't have to call `finalize()` or try to replace the configurator instance. You should remove the last two lines to avoid any possible side-effects.

You can test whether a plugin has been loaded by testing whether it was set with `isset($configurator->PluginName)` where `PluginName` is the name of the plugin such as `BBCodes` or `Litedown`.

**Comment by johnd0e** [comment]
Thanks!
And how should I check if some rules generator is already added?

**Comment by JoshyPHP** [comment]
With [contains()](http://s9e.github.io/TextFormatter/api/s9e/TextFormatter/Configurator/RulesGenerator.html#method_contains):

```php
var_dump($configurator->rulesGenerator->contains('IgnoreTagsInCode'));
```
