### ISSUE TITLE
List of BBCodes

### ISSUE THREAD

**Issue by the-turk** [s9e/TextFormatter#131]
Is there any way to list all of BBCodes including all of the custom ones?

**Comment by JoshyPHP** [comment]
There are no BBCodes set by default but there's a list of BBCodes bundled with the library at https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Add_from_the_repository/

**Comment by the-turk** [comment]
What i'm trying to say is... Can i list all of the activated (or which is added from repository) BBCodes programmatically? Like this:

`$configurator->BBCodes->getAll();`

**Comment by JoshyPHP** [comment]
There's no API for it but you can find the file it's based on at [src/Plugins/BBCodes/Configurator/repository.xml](https://github.com/s9e/TextFormatter/blob/master/src/Plugins/BBCodes/Configurator/repository.xml)

**Comment by the-turk** [comment]
I'm trying to write an _BBCode Manager_ extension for Flarum. There are sooo many BBCodes extension (almost 1 extension for 1 BBCode) and i want to list all of the BBCodes shipped with these extensions. Is there a way to do so?

**Comment by JoshyPHP** [comment]
Not unless they ship their BBCode definitions as a custom repository, which they almost certainly don't because I have put no emphasis on that feature so the developers may not even be aware it exists.

You can list BBCodes that have been *set* (IOW added) and the corresponding tag. You may be able to create an empty configurator and feed it to the extension's event listener in order to inspect the BBCodes/tags they create.

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addFromRepository('B');
$configurator->BBCodes->addFromRepository('URL');
foreach ($configurator->BBCodes as $bbcodeName => $bbcode)
{
	$tagName = $bbcode->tagName;
	$tag     = $configurator->tags[$tagName];

	echo "[$bbcodeName]\t<$tagName>\t", $tag->template, "\n";
}
```
```
[B]     <B>     <b><xsl:apply-templates/></b>
[URL]   <URL>   <a href="{@url}"><xsl:copy-of select="@title"/><xsl:apply-templates/></a>
```

**Comment by the-turk** [comment]
Great! Thank you.

**Comment by the-turk** [comment]
here's an another question: can i update a tag's template which have been set before?

`$tag->template = $newTemplate;`
