### ISSUE TITLE
Link to Custom_BBCode_syntax is broken

### ISSUE THREAD

**Issue by johnd0e** [s9e/TextFormatter#132]
https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Synopsis/ has link to  (https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Synopsis/Custom_BBCode_syntax/), which is broken.

I see source file exists: [Custom_BBCode_syntax.md](https://github.com/s9e/TextFormatter/blob/master/docs/Plugins/BBCodes/Custom_BBCode_syntax.md), so it's probably some docs generation error.

**Comment by JoshyPHP** [comment]
Good catch, it should be fixed now. :+1:
