### ISSUE TITLE
Link to "phpBB's custom BBCodes" page is broken

### ISSUE THREAD

**Issue by johnd0e** [s9e/TextFormatter#133]
https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Synopsis/ links to https://www.phpbb.com/customise/db/custom_bbcodes-26/

As I found trailing backslash is not needed, so right url is https://www.phpbb.com/customise/db/custom_bbcodes-26

**Comment by JoshyPHP** [comment]
Should be fixed by d00dd02475acda15c1203f12cd563f6987cdfa79

**Comment by johnd0e** [comment]
I see exactly same issue on page https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Add_custom_BBCodes/
