### ISSUE TITLE
Litedown: spoiler title

### ISSUE THREAD

**Issue by johnd0e** [s9e/TextFormatter#134]
https://s9etextformatter.readthedocs.io/Plugins/Litedown/Syntax/#spoilers

I propose to extend spoiler syntax to (optionally) specify titles. 
For example: 

```md
>!(title1) >!(title2) Super spoiler
>!
>! Spoiler

No spoiler
```

Specified titles should be transformed into [summary](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary) tags.

**Comment by JoshyPHP** [comment]
The syntax for spoilers (and pretty much everything else in Litedown) is based on existing implementations. I'd rather not add a new independent syntax unless it's particularly useful, so I don't intend to implement this one. In this case I'd recommend using a BBCode instead.

It's theoretically possible to implement this syntax in userland but supporting multiple titles on the same line is complicated and I don't think it's worth pursing. Alternatively, it's possible to use a different grammar and rely on existing features. For example, if the first element of a spoiler is a H1 header then its text content is used as title:
```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->Litedown;
$configurator->tags['spoiler']->template = '<details>
	<xsl:if test="name(*[1]) = \'H1\'">
		<summary><xsl:value-of select="*[1]"/></summary>
	</xsl:if>
	<xsl:apply-templates/>
</details>';

extract($configurator->finalize());

$text = '>! # Title
>!
>! Content';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<details><summary>Title</summary><h1>Title</h1>

<p>Content</p></details>
```
This is purely for illustration purposes, I don't intend to implement that syntax either.

**Comment by johnd0e** [comment]
> The syntax for spoilers is based on existing implementations.

Could you point me to some of markdown spoiler implementation?


> This is purely for illustration purposes,

So it's possible to write an extension to enable this?

**Comment by JoshyPHP** [comment]
The spoiler syntax is primarily based on [Discord's](https://support.discordapp.com/hc/en-us/articles/360022320632-Spoiler-Tags-) and [Reddit's](https://old.reddit.com/wiki/markdown#wiki_quick_reference) (including the [block spoilers](https://meta.stackexchange.com/questions/72877/whats-the-exact-syntax-for-spoiler-markup#answer-72878) that were lost during Reddit's redesign.)

You can create an extension for almost anything you want, including this feature. The more complicated the feature, the more complex the implementation and the more code you have to write. That's why I generally recommend sticking to simple stuff.

**Comment by johnd0e** [comment]
Just found that following now is considered as valid spoiler:
```md
>!content
```

Is it intended?
I supposed that whitespace between `>!` and `content` is mandatory, to exclude false triggering.

**Comment by JoshyPHP** [comment]
Yes, it's intended to follow the same rules as the blockquote syntax. You can use `> !content` or `>\!content` to start the content of a blockquote with an exclamation mark.

**Comment by johnd0e** [comment]
> For example, if the first element of a spoiler is a H1 header then its text content is used as title:

Is it possible to remove first element (it is not needed as it's already in spoiler title)?

**Comment by JoshyPHP** [comment]
You can never *remove* elements but you can ignore or skip them. You can choose which nodes are processed via `xsl:apply-templates`:

```xsl
<xsl:apply-templates select="node()[position() &gt; 1]"/>
```

With that said, this is not something I recommend using.

**Comment by johnd0e** [comment]
Thanks!
I've ended up with such template:
```html
<details>
<xsl:choose>
	<xsl:when test="name(*[1]) = \'H1\'">
		<summary><xsl:value-of select="*[1]"/></summary>
		<xsl:apply-templates select="node()[position() &gt; 1]"/>
	</xsl:when>
	<xsl:otherwise>
		<xsl:apply-templates/>
	</xsl:otherwise>
</xsl:choose>
</details>';
```
