### ISSUE TITLE
Question about issue with external css

### ISSUE THREAD

**Issue by johnd0e** [s9e/TextFormatter#135]
My sample may look strange, but I'am just trying to understand why embedded style has different impact than external css.

For test purposed I have bbcode for inline-styled div:
<details><summary>[div] bbcode</summary>

```
[div]{TEXT}[/div]
```
```html
<div style="display:inline">
{TEXT}
</div>
```

</details>

And I have message with such source:
```bbcode
sample [div]div[/div]
new line
```
It renders without surprises (there is `<br>` between lines):
<details>

```
sample div
new line
```
</details>

But then I replace embedded style with (external) css:
<details>

```html
<div class="inline-div">
{TEXT}
</div>
```
```css
.inline-div {display:inline}
```
</details>

And now same source renders without `<br>`:
```
sample div new line
```

Perhaps TextFormatter uses some heuristic method, inspecting embedded styles of tags, trying to decide whether element is inline-type or block-type?
If so, is it possible to override this behavior? (I tried to apply some [tag rules](https://s9etextformatter.readthedocs.io/Rules/Tag_rules/) to my bbcode, but without success)

**Comment by JoshyPHP** [comment]
Block elements usually have a [ignoreSurroundingWhitespace](https://s9etextformatter.readthedocs.io/Rules/Rules_generators/) rule automatically created. This is to make markup such as `[quote]` or `[code]` block more flexible to the users when formatting their text. For example, it allows more breathing room when quoting a previous message as such:
```
[quote]
Quoted message
[/quote]

Response.
```

Elements that are not considered block (for example, markup for bold and italic) are expected to be used inline and do not receive this rule automatically. If an element is marked as `display:inline` or `display:block` via inline CSS, the element is generally treated as such.

You can always override automatic rules one way or another when creating a new BBCode. For example:
```
[div #ignoreSurroundingWhitespace=false]{TEXT}[/div]
```
