### ISSUE TITLE
lazy load for MediaPack

### ISSUE THREAD

**Issue by BigMinnie** [s9e/TextFormatter#143]
I have a page with tons of videos (100+) and opening that page it's not nice, because it's loading all videos at the same time, it lags the page. So I'm asking if there could be something done with this? Maybe some lazy loading that starts loading the video only if you click on it?

**Comment by JoshyPHP** [comment]
Nothing like that planned in the foreseeable future. You can't detect clicks on an iframe so you'd have to create a placeholder, or perhaps more simply only load iframes that are in view. Or you could [use a template normalization](https://s9etextformatter.readthedocs.io/Templating/Template_normalization/Change_default/#add-your-own-custom-normalization) to [make all iframes lazy](https://web.dev/native-lazy-loading/) by default.

**Comment by JoshyPHP** [comment]
For what it's worth, I have a XenForo add-on that implements lazy loading at rendering time.

[PHP source here](https://github.com/s9e/xenforo-ext-media-sites/blob/master/addon/Helper.php#L65-L96), [JavaScript there](https://github.com/s9e/xenforo-ext-media-sites/blob/3455ad79f37ede7d6c23c0c166ba8e8759b489bf/src/LazyLoad.js#L1).

**Comment by BigMinnie** [comment]
Ok, thanks, will check it out.

**Comment by JoshyPHP** [comment]
Starting with 2.6.0, all iframes from the MediaEmbed plugin use native lazy loading. It's not quite as efficient as a dedicated solution but it's basically free and works on [all modern browsers except Safari](https://caniuse.com/#feat=loading-lazy-attr).
