### ISSUE TITLE
Using data- attributes with BBCodes

### ISSUE THREAD

**Issue by the-turk** [s9e/TextFormatter#144]
Hello,

I want to add an optional `data-` attribute to URL BBCodes. It should be look like this:

**Input:**

```
[URL={URL;useContent} title={TEXT?} lightbox={CHOICE=true,false;optional}]{TEXT}[/URL]
```

or (maybe?):

```
[URL={URL;useContent} title={TEXT?} data-lightbox;optional]{TEXT}[/URL]
```

**Output:**

```
<a data-lightbox href="{@url}"><xsl:copy-of select="@title" /><xsl:apply-templates /></a>
```

I know I can modify its template as you've explained [here](https://s9etextformatter.readthedocs.io/Templating/Modify_a_template/) but I have no idea about changing its usage.

**Comment by JoshyPHP** [comment]
What's the error message? I suppose it's something about the XSL being invalid. XSL doesn't support minimized attributes, you have to give them an empty value like so:

```xsl
<a data-lightbox="" href="{@url}"><xsl:copy-of select="@title" /><xsl:apply-templates /></a>
```

**Comment by the-turk** [comment]
oh sorry, I didn't make myself clear. I still couldn't find a proper way to implement it. My question was about overriding its usage - so there are no outputs actually, that's my desired output which I am trying to achieve.

**Comment by JoshyPHP** [comment]
Can you provide examples of what a user would type (in BBCodes) and how it should be rendered in  HTML?

**Comment by the-turk** [comment]
**Input:**

`[URL="https://www.github.com" data-lightbox]GitHub[/URL]` 

or

`[URL="https://www.github.com" lightbox="true"]GitHub[/URL]` 

(whichever is possible, former is preferred)

**Output:**
```
<a href="https://www.github.com" data-lightbox>GitHub</a>
```

**Comment by JoshyPHP** [comment]
So what you're trying to do is have an HTML attribute if a BBCode attribute is set to `true`, correct? Something like this would work:

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addCustom(
	'[URL={URL;useContent} title={TEXT?} lightbox={CHOICE=true,false;optional}]{TEXT}[/URL]',
	'<a href="{@url}">
		<xsl:copy-of select="@title" />
		<xsl:if test="@lightbox = \'true\'">
			<xsl:attribute name="data-lightbox"/>
		</xsl:if>
		<xsl:apply-templates />
	</a>'
);

extract($configurator->finalize());

$text = "[URL=https://www.github.com]GitHub[/URL]\n"
      . "[URL=https://www.github.com lightbox=true]GitHub[/URL]\n"
      . "[URL=https://www.github.com lightbox=false]GitHub[/URL]";
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<a href="https://www.github.com">GitHub</a>
<a href="https://www.github.com" data-lightbox="">GitHub</a>
<a href="https://www.github.com">GitHub</a>
```

You can also consider defining a default value with `lightbox={CHOICE=true,false;optional;defaultValue=true}`.

**Comment by the-turk** [comment]
Thank you so much! But I've one concern:  If I add this tag as a custom BBCode, will it override the same BBCode which has been added from bundled repository before? Which one has higher priority, custom one or the bundled one? I'm asking this because I'm using Flarum with [this extension](https://github.com/flarum/bbcode/blob/165c47059e1f44cae56cc5462366c92ca96dcc33/extend.php#L19) and it also adds an URL BBCode from bundled repository.

**Comment by JoshyPHP** [comment]
It depends on which order the code is executed. Whichever BBCode is declared last will overwrite the previous definition. If you overwrite Flarum's default BBCode you will probably regret it. Modify it instead.

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addFromRepository('URL');

$tag = $configurator->tags['URL'];
$attribute = $tag->attributes->add('lightbox');
$attribute->required = false;
$attribute->filterChain->append('#choice')->setValues(['true', 'false']);

$tag->template = preg_replace(
	'(^<[^>]++>\\K)',
	'<xsl:if test="@lightbox = \'true\'"><xsl:attribute name="data-lightbox"/></xsl:if>',
	$tag->template
);

extract($configurator->finalize());

$text = "[URL=https://www.github.com]GitHub[/URL]\n"
      . "[URL=https://www.github.com lightbox=true]GitHub[/URL]\n"
      . "[URL=https://www.github.com lightbox=false]GitHub[/URL]";
$xml  = $parser->parse($text);
$html = $renderer->render($xml);$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```

**Comment by the-turk** [comment]
That's it! Thanks again.
