### ISSUE TITLE
Scrape a frame

### ISSUE THREAD

**Issue by rxu** [s9e/TextFormatter#146]
Am I getting right that if a sensitive information (like identifiers/hashes/etc) is in a frame then scraping it is not possible apparently? As an example: `https://vk.com/video121599878_165723901`.

**Comment by JoshyPHP** [comment]
Anything that's publicly accessible can be scraped. As I recall, VK has been very inconsistent about making their secret hash publicly accessible that's why you need the full URL to embed VK videos.

**Comment by rxu** [comment]
I found out if you follow the example link above you'll get a frame which source (in JQuery/Ajax part of code) contains the missing hash of the video, like `"embed_hash":"e06b0878046e1d32"`.
Hence I thought it could be scraped somehow to prepare full video url. But straight scraping the `https://vk.com/video121599878_165723901` doesn't yield the frame source code.

**Comment by JoshyPHP** [comment]
You can scrape any URL. What's the URL that contains the hash for that video?

https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/#specify-a-different-url-for-scraping

**Comment by rxu** [comment]
It's `https://vk.com/video121599878_165723901` but it's with the browser. As far as I get it the frame is getting additionally loaded by Ajax or something like that.

**Comment by JoshyPHP** [comment]
But what's the frame's URL that needs to be scraped?

**Comment by rxu** [comment]
> I assume that the goal is to be able to type `https://vk.com/video121599878_165723901` and have the library find the embed hash, right?

Yup.

> But what's the frame's URL that needs to be scraped?

Couldn't get one somehow as it just opens by the link I pointed above. Sorry.

**Comment by JoshyPHP** [comment]
If the embed_hash is in the original page it can be scraped directly. I ran a couple of tests and VK is a bit fickle and likes to respond with a 418 error. Or sometimes they block me and I have to go through a VPN for some reason.

I may reinstate unofficial support for hash-less URLs but that's not something I'd keep a regression test for. WIP is at https://github.com/s9e/TextFormatter/commit/24b8e647f7e156b6ec32642d8335ec6eabda6ad0
