### ISSUE TITLE
Support CodePen in MediaEmbed

### ISSUE THREAD

**Issue by locness3** [s9e/TextFormatter#148]

**Comment by JoshyPHP** [comment]
What's your use case for CodePen? I've never used this site.

How would you expect a link to CodePen to be embedded as? Which tabs, what size?

**Comment by locness3** [comment]
Ah yes, there's the tabs problem 😬

My use case is that I run a coding-related forum which uses Flarum, and so it uses TextFormatter.

**Comment by JoshyPHP** [comment]
I'm generally favorable to adding CodePen since I already support GitHub's Gist and they target the same audience. I'm probably going to add it with the HTML + result tabs by default, with a 400 px height.
