### ISSUE TITLE
Customize MediaEmbed language

### ISSUE THREAD

**Issue by rxu** [s9e/TextFormatter#149]
Just noticed I have media embedded in [default] `en` language. Is there a way to set the media content language to the site language where possible?
As an example, embedded twit is in `en` while the site lang is `ru`.

![lang](https://user-images.githubusercontent.com/212322/86995074-4dc0df00-c1d2-11ea-868b-84c1e02f4902.png)

**Comment by JoshyPHP** [comment]
I have no plans to make it customizable externally but [the iframe sets Twitter's UI to the browser's preferences](https://github.com/s9e/s9e.github.io/blob/0ff8790f2e884b64948edc87f5e8fd762a776345/iframe/2/twitter.html#L9). What's the value of your `navigator.language`?

**Comment by rxu** [comment]
> What's the value of your `navigator.language`?

Oh nice. It `en`, so changing it to `ru` changes the iframe language respectively. Thanks for clarification.
