### ISSUE TITLE
Escaping Litedown

### ISSUE THREAD

**Issue by Fastidious** [s9e/TextFormatter#15]
How can I escape Litedown Markdown? In Markdown that is accomplished by using a backslash, like \*bold\* (not). Thanks!

**Comment by s9e** [comment]
The [Escaper](http://s9etextformatter.readthedocs.org/Plugins/Escaper/Synopsis/) plugin. You can see it in action [in that demo](http://s9e.github.io/TextFormatter/fatdown.html).
