### ISSUE TITLE
Vocaroo Broken

### ISSUE THREAD

**Issue by diegaless** [s9e/TextFormatter#150]
When I try to publish a link from Vocaroo, whether or not with the media tag when previewing or publishing a post, the link simply comes out or, failing that, the tags media link to vocaroo media.

other sites work properly( Instagram, Twitter, youtube..)

If you think that a support template is necessary, I will gladly add it, but as the other sites work, I suppose it is a matter of changes in the vocaroo api. My site running phpBB 3.3.0

I really appreciate the work you have done with this library, it is not trivial at all and if you are very professional how you handle the issue of all parsing! Great job

**Comment by JoshyPHP** [comment]
What's the URL that doesn't work? I didn't read the rest, the only relevant part is the URL.

**Comment by diegaless** [comment]
Tried for example this:
https://vocaroo.com/nMgU7fAiqyh

And this other url in your supported sitted they don't work either:
https://vocaroo.com/nMgU7fAiqyh

no link from vocaroo works

**Comment by JoshyPHP** [comment]
It works for me, using this script:
```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->MediaEmbed->add('vocaroo');

extract($configurator->finalize());

$text = 'https://vocaroo.com/nMgU7fAiqyh';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```

If it doesn't work in phpBB, it's possible that phpBB uses an outdated version of the library or that it does not enabled Vocaroo.

**Comment by diegaless** [comment]
PHPbb does support it, I guess they used an outdated version. Thank you!
I will report it to them so they can fix it in the next versions
