### ISSUE TITLE
Is possible to disable ManageParagraphs rule at parsing time?

### ISSUE THREAD

**Issue by AlfredoRamos** [s9e/TextFormatter#151]
Hi,

Is there any built-in method to disable the `ManageParagraphs` rule, enabled by the Litedown plugin, at parsing time?

Some context:

I'm using the Litedown plugin for a Markdown extension for phpBB. In the posting options I have a checkbox "Disable Markdown" that when checked I call `Parser::disablePlugin(...)` to, as the method says, disable said plugins when for some reason the user wants to disable Markdown completely.

https://github.com/AlfredoRamos/phpbb-ext-markdown/blob/abb24f82e885cfc03faf2da502ba77788979db1f/event/listener.php#L295-L298

That works as expected, except that the `ManageParagraphs` rule is still enabled, and that's not desirable for some users.

https://github.com/s9e/TextFormatter/blob/d7728a6d25a01ee15d9aeb2428551acd4f567c71/src/Plugins/Litedown/Configurator.php#L109

I've been digging in the code to find a built-int method to do something similar (`Parser::disablePlugin()`) but with the plugin rules.

I'm not sure if using `ArrayIterator::offsetUnset()` would work:

```
$configurator->rulesGenerator->offsetUnset('ManageParagraphs');
```

And I can't test it right now since the phpBB event I'm using only exposes the renderer, not the configurator. So before I try to figure out how to reliably get it, I though it would be better idea to ask first.

**Comment by JoshyPHP** [comment]
The short answer is no, rules are defined during configuration and there's no API to change them at parsing time.

The library is designed so that if you need different set of rules and markups, you can a different parser instance. That's not really possible in phpBB though, unless you want to mess with the `textformatter` service.

**Comment by AlfredoRamos** [comment]
I see, I'll leave it as is then.

Thank you ;)
