### ISSUE TITLE
Struggling to remove default site

### ISSUE THREAD

**Issue by pepper-forms** [s9e/TextFormatter#152]
Please tell me, where do I put this code?
```
$configurator = new s9e\TextFormatter\Configurator;
$configurator->MediaEmbed->defaultSites->delete('imgur');
```
in order to delete imgur from mediaembed plugin?

**Comment by JoshyPHP** [comment]
It's PHP code, so anywhere PHP is executed. How do you use this library?

**Comment by pepper-forms** [comment]
> It's PHP code, so anywhere PHP is executed. How do you use this library?

I use it as extension on my phpbbex (phpbb 3.1.9) forum. Got it from this link https://www.phpbb.com/community/viewtopic.php?f=501&t=2272431&hilit=remove&start=30.

Im total zero at php, where can I put it? Like some file in root folder or edit extension files?

**Comment by JoshyPHP** [comment]
You can't do anything if you're not a programmer. That extension and your version of phpBB are abandoned. Your only option is to upgrade to a recent version of phpBB and install their version of the extension.

**Comment by pepper-forms** [comment]
> You can't do anything if you're not a programmer. That extension and your version of phpBB are abandoned. Your only option is to upgrade to a recent version of phpBB and install their version of the extension.

What do you mean by "their version" I thought its ur project, you literally the author of the post. This extension works great on my forum, the only problem is that I want to remove one site, documentation says its possible.

**Comment by JoshyPHP** [comment]
It's possible for programmers. This library is for programmers. I don't know what phpbbex is. The extension you're using has been abandoned a long time ago.

**Comment by pepper-forms** [comment]
> It's possible for programmers. This library is for programmers. I don't know what phpbbex is. The extension you're using has been abandoned a long time ago.

phpbbex is modded 3.1.9 phpbb. All phpbb extensions work here. I know this thing is abandoned, but a lot of people still use it. I don't have ability to upgrade my forum right now, and your project have no alternatives on this version. So I'll be very grateful if you can help me find the way to change configurator, so it doesn't apply any changes to imgur urls. 
Accordingly to this [docs](https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Using_default_sites/) I can modify default sites collection, but where can I use this code?

This is root folder 
![image](https://user-images.githubusercontent.com/50184364/92015016-d4b8b080-ed58-11ea-93e3-1b81f27c1174.png)
This is extension folder
![image](https://user-images.githubusercontent.com/50184364/92015669-d33bb800-ed59-11ea-892f-8a65ad8e3c9d.png)

**Comment by JoshyPHP** [comment]
Sorry but the documentation is for programmers so your only option is to hire one.

**Comment by JoshyPHP** [comment]
To be clear, in case I wasn't. phpBB 3.1.9 dates back to 2016. If you upgrade to a modern version of phpBB and [install their extension](https://www.phpbb.com/extensions/official-extensions/) you won't have to ask somebody to create custom code for you.
