### ISSUE TITLE
Dumpert

### ISSUE THREAD

**Issue by MaxstarPCW** [s9e/TextFormatter#155]
https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Sites/#dumpert

Dumpert has changed the URL format.

`https://www.dumpert.nl/mediabase/6622577/4652b140/r_mi_gaillard_doet_halloween_prank.html`

redirects to:

`https://www.dumpert.nl/item/6622577_4652b140`

**Comment by JoshyPHP** [comment]
I'm looking at dumpert and it appears they have removed the ability to embed their video. I don't know whether this is an accident or they intentionally shut it down.
