### ISSUE TITLE
Spotify no longer embedded

### ISSUE THREAD

**Issue by danielunited** [s9e/TextFormatter#156]
Hi there! I'm using [FriendsOfFlarum/formatting](https://github.com/FriendsOfFlarum/formatting) which is using TextFormatter to format links. Loving it so far!

I've recently noticed that Spotify's mobile app generates links as "link.tospotify.com" which are not embedded (for example: https://link.tospotify.com/fzU48B0mLbb)

Can you please add support to it? 🙏

**Comment by JoshyPHP** [comment]
The new links are already supported in the latest version. Check out with Flarum's support about how to update your local dependencies.
