### ISSUE TITLE
The deviceorientation events are blocked by feature policy.

### ISSUE THREAD

**Issue by czuczuczu** [s9e/TextFormatter#157]
Hi, when i try play full screen video, for example streamable, the screen goes black and i receive this error message (from chrome remote debugging):

`The deviceorientation events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features`

I am using most recent files from repo.

Is there anything i can do to resolve this problem? Thanks!

**Comment by JoshyPHP** [comment]
Where does that error orginate from? You could try modifying the `allow` attribute on the site's iframe but I don't know what keyword enables orientation events.

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->MediaEmbed->add('streamable');

$dom = $configurator->tags['STREAMABLE']->template->asDOM();
$dom->firstOf('//iframe')->setAttribute('allow', 'fullscreen *; accelerometer *; magnetometer *; gyroscope *');
$dom->saveChanges();

extract($configurator->finalize());

$text = 'https://streamable.com/e4d';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<span data-s9e-mediaembed="streamable" style="display:inline-block;width:100%;max-width:640px"><span style="display:block;overflow:hidden;position:relative;padding-bottom:56.25%"><iframe allowfullscreen="" loading="lazy" scrolling="no" src="//streamable.com/e/e4d" style="border:0;height:100%;left:0;position:absolute;width:100%" allow="fullscreen *; accelerometer *; magnetometer *; gyroscope *"></iframe></span></span>
```

**Comment by czuczuczu** [comment]
Thanks for reply. 

I am using your repo in phpbb board enabled by this plugin:
https://github.com/s9e/phpbb-ext-mediaembed

**Comment by JoshyPHP** [comment]
I've just checked Streamable's website and their recommended "Embed" code doesn't require any specific permissions:
```html
<div style="width: 100%; height: 0px; position: relative; padding-bottom: 56.250%;"><iframe src="https://streamable.com/e/z1plzy" frameborder="0" width="100%" height="100%" allowfullscreen style="width: 100%; height: 100%; position: absolute;"></iframe></div>
```

I'm closing this issue on the assumption this is a issue in Streamable's code but let me know if you find otherwise.
