### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by tobscure** [s9e/TextFormatter#16]
It would be helpful if you could tag v0.1.0 and start semver. This would allow me/others to `composer require` the package with `"minimum-stability": "stable"`, and without the `@dev` suffix for the package version (which is causing problems for me given that TextFormatter is a sub-dependency).

**Comment by s9e** [comment]
I'll tag the release/php5.3 branch as `0.1.0` later.

**Comment by s9e** [comment]
Release tagged. https://github.com/s9e/TextFormatter/releases/tag/0.1.0
