### ISSUE TITLE
[Documentation] Enabling BBCode after Tasklists breaks Tasklists

### ISSUE THREAD

**Issue by askvortsov1** [s9e/TextFormatter#160]
Tasklists recently broke for me after working quite well; I did some investigation and found that it was only broken when the BBCode plugin was triggered after it. I'm assuming BBCode overrides some attributes of the `LI` tag added by TaskLists. I don't think this is that problematic an issue in and of itself, but mentioning it in the documentation for TaskLists might help avoid issues.

**Comment by JoshyPHP** [comment]
The TaskLists plugin relies on the `LI` tag to function. When the TaskLists plugin is loaded, it adds a tag filter to `LI` and modifies its template. If `LI` is overwritten, those changes have to be reapplied. BBCodes can be created without overwriting tags (e.g. `$configurator->BBCodes->add('*')->tagName = 'LI';`) but methods such as `addCustom()` or `addFromRepository()` do overwrite them by default.

I've just updated the TaskLists plugin to check `LI` at the end of configuration and reapply the modifications if necessary. That should fix that particular issue without causing any likely side effects.
