### ISSUE TITLE
XML Parsing Error: mismatched tag. Expected: </iframe>.

### ISSUE THREAD

**Issue by iPurpl3x** [s9e/TextFormatter#161]
Since I updated to `s9e/text-formatter 2.9.1`, I have an issue with Firefox. All other browsers seem fine (tested : Chrome, Safari).

I get the following error : 

![image](https://user-images.githubusercontent.com/18526076/118450139-2b51f900-b6f4-11eb-9b0f-49bf41bd35f7.png)

FYI: here, this library is being used inside of [Flarum](https://github.com/flarum/core), with the [`fof/formatting`](https://github.com/FriendsOfFlarum/formatting) extension. 

If more information for debugging is required, just let me know.

**Comment by JoshyPHP** [comment]
Check out this page, does it work? https://s9e.github.io/TextFormatter/fatdown.html

I've just installed the latest available Flarum via Composer and things generally seem to work. What would be the exact steps to reproduce this error? What plugins do I have to enable and what actions need to be performed to get this error?

**Comment by JoshyPHP** [comment]
Actually, if you can attach your `forum-c99a8d9f.js` file that should be enough for me to figure out what's going on.

**Comment by iPurpl3x** [comment]
Here is a link to my [forum-6c3d4799.js](https://we.tl/t-Q8FQyuUKYM).
I'm using Flarum beta.15 here.

I get the error when loading the page, any page does that so it's a bit difficult to know what causes it. When disabling MediaEmbed the error is gone, so it must be due to some changes made to that plugin.

**Comment by JoshyPHP** [comment]
There are issues with that file, parts of the code are missing. Check out with Flarum how to disable JavaScript minification to see if that fixes it.

**Comment by JoshyPHP** [comment]
As a temporary workaround, you can try editing `vendor/flarum/core/src/Formatter/Formatter.php` and replace `MatthiasMullieMinify` with `ClosureCompilerService`.
```diff
diff --git a/src/Formatter/Formatter.php b/src/Formatter/Formatter.php
index d2396ea2..38442fb1 100644
--- a/src/Formatter/Formatter.php
+++ b/src/Formatter/Formatter.php
@@ -152,7 +152,7 @@ class Formatter
         $configurator->enableJavaScript();
         $configurator->javascript->exports = ['preview'];
 
-        $configurator->javascript->setMinifier('MatthiasMullieMinify')
+        $configurator->javascript->setMinifier('ClosureCompilerService')
             ->keepGoing = true;
 
         $configurator->Escaper;
```

The downside is that using `ClosureCompilerService` will take a few seconds to minify JavaScript and depending on your server's configuration it may stops halfway through. In that case, you'd have to remove that line completely, including `->keepGoing = true;`

**Comment by JoshyPHP** [comment]
After some digging, I found a bug in my code that explains why there are missing chunks in your file and why mine was fine. I've just published an update that should fix it. If you want to test it for yourself, I don't think you can install it via composer but if you feel adventurous you can download the new file directly from GitHub by running the following command in CLI at the root of your Flarum installation:

```bash
curl https://raw.githubusercontent.com/s9e/TextFormatter/5df3c57b9e1b249823fb2025733d8fe039797287/src/Configurator/JavaScript/StylesheetCompressor.php > vendor/s9e/text-formatter/src/Configurator/JavaScript/StylesheetCompressor.php
```

It will replace the file in `vendor/s9e/text-formatter/src/Configurator/JavaScript/StylesheetCompressor.php` with the one from this commit: https://github.com/s9e/TextFormatter/commit/5df3c57b9e1b249823fb2025733d8fe039797287

Please feel free to reopen this issue if you still encounter this bug and/or update it with new information if applicable.

**Comment by iPurpl3x** [comment]
Nice, the update (2.9.2) seems to fix my issue. Thank you @JoshyPHP !
