### ISSUE TITLE
Youtube privacy enhanced mode for GDPR compliance?

### ISSUE THREAD

**Issue by poVoq** [s9e/TextFormatter#164]
Would be nice if this would automatically use the Youtube privacy enhanced mode that does not use cookies and thus is easier to use under GDPR legislation.

See also: https://www.ghacks.net/2018/05/23/why-you-should-always-use-youtubes-privacy-enhanced-mode/

Thanks!

**Comment by JoshyPHP** [comment]
This is something I'd rather leave to the library consumers to decide. See #154 for an example: https://github.com/s9e/TextFormatter/issues/154#issuecomment-727282061
