### ISSUE TITLE
Replacing matched strings in the `CODE` tag

### ISSUE THREAD

**Issue by the-turk** [s9e/TextFormatter#166]
Hi!

I need some suggestions on replacing RegEx matched strings in a code block or an inline code.

`[match] code [match]` => `[replace] code [replace]`

Is this possible by modifying `CODE` tag's template? 

Sorry if this question doesn't make sense, I have zero knowledge about XLST language. Thanks!

**Comment by JoshyPHP** [comment]
No, the content of `CODE` blocks is always used verbatim; It cannot be changed.

If you want to alter its content, you'd have to do it in JavaScript.

**Comment by the-turk** [comment]
Thank you for your time and for this amazing repository! Take care and be safe.
