### ISSUE TITLE
Litedown has priority over BBCode tags

### ISSUE THREAD

**Issue by the-turk** [s9e/TextFormatter#167]
It's not a big deal but...

```
[NOPARSE](test)[/NOPARSE]
[CODE](test)[/CODE]
```
results:

[NOPARSE](test)[/NOPARSE]
[CODE](test)[/CODE]
___
I'm using BBCodes to render TeX typesettings and this issue was noticed while typing `[tex](x,y)[/tex]` by a fluke.

**Comment by JoshyPHP** [comment]
Not all of Litedown but you're correct that the Litedown links have priority over regular BBCodes. The list of special cases is at https://s9etextformatter.readthedocs.io/Internals/Tag_priorities/

Litedown's inline links have priority over BBCodes to prevent the other side of that interaction, i.e. having inline links interpreted has BBCodes. I think it came from a real-world case but I can't find any reference to it. The [test case I have in the repository](https://github.com/s9e/TextFormatter/blob/cf94ea73d02a720020acbeaac703cda61e0450b5/tests/Plugins/Litedown/Parser/Passes/LinksTest.php#L99-L107) is this: `[b](https://en.wikipedia.org/wiki/B) [b]..[/b]`

BBCodes can be [explicitly paired](https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Synopsis/) by using a numeric suffix. I'm thinking about giving those priority over regular markup. You'd be able to use this and be interpreted as intended:
```bbcode
[CODE:123](test)[/CODE:123]
[code](https://en.wikipedia.org/wiki/Code)
```

**Comment by the-turk** [comment]
> Let me know if you have any suggestion or feedback from real-world usage.

I was thinking about checking markdown link syntax if it's followed by a closing BBCode tag at first but I'm not sure if this approach could introduce another problems in the future.

> BBCodes can be explicitly paired by using a numeric suffix. I'm thinking about giving those priority over regular markup.

That's a brilliant idea and I'm totally okay with this!

**Comment by the-turk** [comment]
Could we also add a method like to generate random numeric suffixes on a tag? So that we type [x] and it silently assigns numeric suffix, before rendering?

**Comment by JoshyPHP** [comment]
If you want to automatically add suffixes to BBCodes you'd have to do it in the user interface. If what you're trying to do is somehow always give priority to BBCodes then no, that's not possible.
