### ISSUE TITLE
False markdown parsing

### ISSUE THREAD

**Issue by johnd0e** [s9e/TextFormatter#168]
On our phpBB-powered board I see that such text does not appear on page at all
```
[win.Uuid far.Guids.FileAssocModifyId ]: {1,3,5,8,10,12,14,16,18}
```
I suppose that Litedown considers it as valid href definition.
But it is not valid, you see.

**Comment by JoshyPHP** [comment]
I'll think about it but I don't think I'll change this behaviour. At the syntax level, it doesn't matter whether the URL ends up being valid or not; Anything that looks like a link reference definition is interpreted as one, even if the URL ends up being unusable. As far as I can tell, all the Markdown flavours work the same: [Babelmark 2 example](https://johnmacfarlane.net/babelmark2/?normalize=1&text=..%0A%0A%5Bwin.Uuid+far.Guids.FileAssocModifyId+%5D%3A+%7B1%2C3%2C5%2C8%2C10%2C12%2C14%2C16%2C18%7D%0A%0A..)

If you don't want a special character to be interpreted as markup, you can escape it with a backslash. For example, `\[x]: x` should not become a link reference.

**Comment by johnd0e** [comment]
> Anything that looks like a link reference definition is interpreted as one, even if the URL ends up being unusable

Well, that could be acceptable if we have just markdown here.

But with phpbb we have a mix of bbcode,extensions, etc.

To prevent false triggering the rules should be stricter than for general single-purpose markdown converter, IMHO.

**Comment by JoshyPHP** [comment]
This is the same issue as #169.

**Comment by johnd0e** [comment]
> This is the same issue as #169.

Actually not, because this one is not related to BBCode blocks, and is reproducible in plain text.

And as I'd suggested, it is possible to minimize undesirable effects by making rules slightly stricter.

**Comment by JoshyPHP** [comment]
This is the same underlying issue. Your suggestion cannot be implemented.
