### ISSUE TITLE
XSLT extension dependency

### ISSUE THREAD

**Issue by tobscure** [s9e/TextFormatter#17]
See:
https://gitter.im/flarum/flarum?at=55d90064098731da7020e819
https://gitter.im/flarum/flarum?at=55d98695004c3e375ad057cf

Is the dependency on PHP's XSLT extension a hard one, or can some third-party library be subbed in? Do you have any idea how common the XSLT extension is on shared hosts?

**Comment by s9e** [comment]
It's a soft one. You can change the type of renderer via `$configurator->rendering->engine`. You can choose between `XSLT` (the default) and `PHP`. The templates don't change, they remain XSLT but they are compiled into PHP. You'll need a writable dir to dump the PHP renderer. http://s9etextformatter.readthedocs.org/Internals/PHP_renderer/

You'll need to handle loading the renderer class yourself if its name/path doesn't map to an autoloading strategy.

**Comment by tobscure** [comment]
Fantastic, thanks.

Sorry for using issues to ask questions! Is there another method of communication you'd prefer me to use?

**Comment by s9e** [comment]
If you mention me on Flarum we can discuss things there. It'll make users feel more involved in development too. ;)
