### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by 3D-I** [s9e/TextFormatter#175]
`https://s9etextformatter.readthedocs.io/Filters/URL_features/Blacklist_hosts/`

The link at the bottom is broken

![image](https://user-images.githubusercontent.com/480857/134120583-6cdc5025-03a5-4ff4-8fd7-ab7c4081991c.png)

I guess it should be 
`https://s9etextformatter.readthedocs.io/Plugins/Censor/Synopsis/`

**Comment by JoshyPHP** [comment]
You're right, thanks for the heads-up.
