### ISSUE TITLE
Links without scheme become relative

### ISSUE THREAD

**Issue by franzliedke** [s9e/TextFormatter#18]
Not sure whether this is a bug or intended, but both Markdown and BBCode links without a "http://" prefix become links relative to the current directory; and that's often not useful.

See this topic for an example: https://github.com/flarum/flarum/commit/7739217b3974285fa441bb0e9ed574f4ba22a54c

**Comment by JoshyPHP** [comment]
It's intended. I'll consider adding an option to require a host and/or a scheme.

**Comment by JoshyPHP** [comment]
I'm closing this issue because I don't think I'm going to implement such an option. Currently, the best way to enforce absolute links is to use an attribute filter.

```php
function myfilter($url)
{
	return preg_replace('(^(?!//|\\w+://))', 'http://', $url);
}

$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addFromRepository('URL');
$configurator->tags['URL']->attributes['url']->filterChain->prepend('myfilter');

extract($configurator->finalize());

$text = '[url]www.example.org[/url]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<a href="http://www.example.org">www.example.org</a>
```
