### ISSUE TITLE
Disable autoplay on embeded Reddit posts

### ISSUE THREAD

**Issue by despecial** [s9e/TextFormatter#182]
We are using the Flarum forum and reddit posts are automatically embeded which is fine.
But as soon as they are loaded they are auto playing. Even when they are not in the viewport.
Really annoying and not helpful/user-friendly. A hint to stop this is very appreciated.

**Comment by JoshyPHP** [comment]
You and me both. As far as I can tell, Reddit doesn't provide any way to prevent autoplay. I feel like there should be a way to prevent it via a [Feature Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/autoplay) but I couldn't make it work the last time I tried.

**Comment by despecial** [comment]
I see. What a pain in the ..

Maybe a window.listener which activates the pause button after the embed has loaded?

**Comment by JoshyPHP** [comment]
The library creates an iframe hosted on GitHub, that executes Reddit's JavaScript. Then Reddit's JavaScript creates its own iframe and I don't know how to interact with it to prevent it from autoplaying.

**Comment by despecial** [comment]
I understand. So here is an example code from reddit
`<iframe id="reddit-embed" src="https://www.redditmedia.com/r/maybemaybemaybe/comments/rh7o7a/maybe_maybe_maybe/?ref_source=embed&amp;ref=share&amp;embed=true" sandbox="allow-scripts allow-same-origin allow-popups" style="border: none;" scrolling="no" width="640" height="619"></iframe>`

Would it help to remove allow-scripts from the sandbox attribute?

**Comment by JoshyPHP** [comment]
Not really. It will prevent the video from being created in the first place.

**Comment by JoshyPHP** [comment]
Closing this for now, feel free to reopen if you become aware of a way to prevent Reddit from autoplaying.

**Comment by despecial** [comment]
A serious question: what's the point of closing the issue when it's not fixed?
Maybe others see it and will try to help.

**Comment by JoshyPHP** [comment]
That's because it has little to do with this project. Reddit manually starts videos (it's not actually autoplay as far as I can tell) and does not provide users a way to prevent it. There's nothing to "fix" except convince Reddit to change their way.

**Comment by despecial** [comment]
I see your point but I do not completely agree. 

Your script embeds it with media preview enabled which shows the video (and get's played). 

Alternatively it could easily prevent this behaviour by removing the media preview parameter and only show the post without the direct embeded video. (see sharing options on reddit)

**Comment by JoshyPHP** [comment]
Ok, but then this isn't about autoplay anymore. You're asking for a way to embed Reddit posts without a preview. That's a request I have to decline. The good news is that the library is designed to allow users to configure it the way they like. You can replace the whole definition for Reddit, or simply tweak the template to display it the way you like. The following links explain how to do that:

 - https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/
 - https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Change_template/

If you find a better way to display Reddit embeds, feel free to share it here.

**Comment by despecial** [comment]
Of course it's about the autoplay :D Why would I suggest it then?

Thanks for the template links though..

**Comment by MrStonedOne** [comment]
> Closing this for now, feel free to reopen if you become aware of a way to prevent Reddit from autoplaying.

`<iframe ... allow="autoplay 'none';">`

the docs say its not supported in firefox, but thats just because the docs refer to the header support, which is disabled in firefox by default, iframe allowlist support for autoplay disabling should be supported in all the common user agents

**Comment by JoshyPHP** [comment]
@MrStonedOne Do you have a concrete example where it makes a difference? The last couple of times I tried solutions based on `allow` to block Reddit's autoplay, it didn't work. I tried again for a third time and it does nothing. As I recall from reading through Reddit's JavaScript, the video is started programmatically.

Here's what I tested on Chrome 98 and Firefox 95:
```html
<iframe allow="autoplay 'none'" scrolling="no" src="https://www.redditmedia.com/r/Damnthatsinteresting/comments/s0evbo?embed=true&amp;depth=1" style="border:0;height:610px;width:800px"></iframe>
```

The video autoplayed in both, as long as the browsers are not in Incognito mode. As far as I can tell, the only way to prevent Reddit videos from starting is to disable local storage, but only because it generates JavaScript errors in Reddit's initialization.
