### ISSUE TITLE
How to register new language to highlight.js?

### ISSUE THREAD

**Issue by Xwdit** [s9e/TextFormatter#184]
Hello, I just want to know where I can get the hljs instance and use the hljs.registerLanguage() function to register the new language? Thanks!

**Comment by JoshyPHP** [comment]
Are you talking about the `[CODE]` BBCode? In that case, it uses [hljs-loader](https://github.com/s9e/hljs-loader) to load the highlight.js library. The instance is in the global context but it's loaded and executed dynamically so you'd have to modify the execution in the tag's template I think.

https://s9etextformatter.readthedocs.io/Templating/Modify_a_template/
