### ISSUE TITLE
How about adding support for Google Forms too?

### ISSUE THREAD

**Issue by NathRitobrata** [s9e/TextFormatter#185]
I saw the extension supports Google Spreadsheets among other Google services, but why not supporting Google Forms too? Forms has been extremely useful and productive these days.

**Comment by JoshyPHP** [comment]
I don't think this is something that most users would want to embed. If you want to add support for Google Forms would be to create your own custom definition or replace the Google Docs definition if Google Forms uses the same domain name.

https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/
