### ISSUE TITLE
MediaEmbed: disable URL autoparsing

### ISSUE THREAD

**Issue by MrStonedOne** [s9e/TextFormatter#186]
reopen of #91 as it was closed with an incorrect answer

mediaembed works for both urls and things inside the media bbcode tag, they (and myself since i got to #91 from google) only want to disable url auto-parsing while keeping the [media] tag parsing. #91 was closed with an incorrect (i think) answer giving instructions that seems to me would disable both.

**Comment by JoshyPHP** [comment]
I'm closing this issue as a duplicate. Feel free to reopen #91 if you can verify that it is actually incorrect.
