### ISSUE TITLE
Add support for Google Docs, Slides and Forms

### ISSUE THREAD

**Issue by iMattPro** [s9e/TextFormatter#190]
In addition to Google Sheets, can support be added for the other 3 types of Google Docs?

Docs: https://docs.google.com/document/
Slides: https://docs.google.com/presentation/
Forms: https://docs.google.com/forms/

**Comment by JoshyPHP** [comment]
I don't know, I'm not familiar with Google Docs. Do they offer it as an option?

**Comment by iMattPro** [comment]
Well it already does googlesheets. But only sheets for some reason. Someone tried to add all google doc types [here](https://github.com/phpbb-extensions/mediaembed/pull/84) but it conflicts with the existing googlesheets.

**Comment by JoshyPHP** [comment]
What I mean is that I have a vague idea what "Google Docs" is (a website) but I don't know whether Google Docs allows embedding the things that Google Docs does, and if so, how. Do you have links to actual Google Docs that someone wants to embed? As I recall, Google Forms isn't something that an average user would want.

**Comment by Tatiana5** [comment]
> Do you have links to actual Google Docs that someone wants to embed?

https://docs.google.com/document/d/1ABxX9iByyjRyqpES1pzjj_oOUJFb5kGDvGj5-myZHow/edit
https://docs.google.com/document/d/1ABxX9iByyjRyqpES1pzjj_oOUJFb5kGDvGj5-myZHow/edit?usp=sharing
https://docs.google.com/document/d/e/2PACX-1vRA9ja90DVgDS-2hTC-2d-mu3PfHlOsEh03gQRRL5YI0XZBhBwKRrrF5_6TPhQBUpUvhSs6uv6aVY4k/pub

https://docs.google.com/spreadsheets/d/1eiYrdstJGtyBtwgdcEEqzpjrTK1ewUOXiyP7AECO3E0/edit#gid=0
https://docs.google.com/spreadsheets/d/1eiYrdstJGtyBtwgdcEEqzpjrTK1ewUOXiyP7AECO3E0/edit?usp=sharing
https://docs.google.com/spreadsheets/d/e/2PACX-1vSayrOI1fCAvuVRwvaoN5NPT0MAa1D_Au8eJeuP3HyQKi9mexkn_O5n_s0WBrEuO6TtJcVoV8MXUIg0/pubhtml

https://docs.google.com/presentation/d/134efYUE6b7bnbKc10ND5C2BjPmHukcd4YFAnDFah5KQ/edit
https://docs.google.com/presentation/d/134efYUE6b7bnbKc10ND5C2BjPmHukcd4YFAnDFah5KQ/edit?usp=sharing
https://docs.google.com/presentation/d/e/2PACX-1vTGfsUA_peut7hnf2Rafj7zhItzDhJhiOWgBsANf3N9NOOB4x9M1oD838Y7VCCW8ou8lu3ODTrqs__E/pub?start=false&loop=false&delayms=3000

https://docs.google.com/forms/d/e/1FAIpQLSfT-l_ho_byoT7NfG8xqlLOgSfOHRD6WUaM20yaRdux_uB0UA/viewform?usp=sf_link
https://docs.google.com/forms/d/e/1FAIpQLSfT-l_ho_byoT7NfG8xqlLOgSfOHRD6WUaM20yaRdux_uB0UA/viewform?embedded=true

It is all types of links for Google documents

**Comment by JoshyPHP** [comment]
Apparently the half of them cannot be embedded.

**Comment by Tatiana5** [comment]
All of the above links can be embedded. The first link is from the address bar, the second is from the "share" button, the third is from the iframe. Missing first link for google forms, it's not intended for embedding

**Comment by JoshyPHP** [comment]
Ok, can you describe to me how someone goes from `https://docs.google.com/presentation/d/134efYUE6b7bnbKc10ND5C2BjPmHukcd4YFAnDFah5KQ/edit` to something that can be embedded? I cannot stress enough that I do not use Google Docs, I barely know what it is and I have never seen it used so I'm operating on virtually no information here.

**Comment by Tatiana5** [comment]
The page is embedded "as is", there is no transition to another type of link 

I made a little mistake with the 3rd link for presentations. This one fits https://docs.google.com/presentation/d/e/2PACX-1vS0QQFJ0f67LYWf9IT8VTi-v3EX1AppFidJX52ruoveVa3Mli_OwE_wFDRTeMl8TElC1ivgRfHDlEJB/embed?start=false&loop=false&delayms=3000 

Result from 1st link: 
![изображение](https://user-images.githubusercontent.com/5697985/156058560-da14d812-aaf6-4e71-83c2-cba5cd6fbf01.png)

Result from 3rd link: 
![изображение](https://user-images.githubusercontent.com/5697985/156058634-6173baf2-abb3-4cd8-951f-850baed8827c.png)

> I should also add that if you've written a custom definition for it, it's fine if you keep using it. I don't think that too many people would benefit from more types of Google Docs being supported by default, especially if it only concerns people who do not use phpBB.

A separate solution requires disabling the built-in for Google Spreadsheets, and at the same time tables in old posts stop working

**Comment by Tatiana5** [comment]
Types of links that cannot be embedded (this is not taken into account in my solution):

https://docs.google.com/presentation/d/e/2PACX-1vS0QQFJ0f67LYWf9IT8VTi-v3EX1AppFidJX52ruoveVa3Mli_OwE_wFDRTeMl8TElC1ivgRfHDlEJB/pub?start=false&loop=false&delayms=3000

https://docs.google.com/forms/d/1BvtKOhvz1NYcm6eBbmoUHsTursaB0po995QTRx4mp4o/edit?usp=forms_home&ths=true

**Comment by JoshyPHP** [comment]
I thought about it carefully but I'm concerned about the long term maintenance so that's something I'd rather leave to each admin to decide how to handle.
