### ISSUE TITLE
MediaEmbed: support tube.switch.ch

### ISSUE THREAD

**Issue by iPurpl3x** [s9e/TextFormatter#191]
Would it be possible to add support for https://tube.switch.ch/ ? @JoshyPHP ? Should be pretty straightforward I think.

**Comment by JoshyPHP** [comment]
It looks like a fairly niche website so that's something I'd rather leave to webmasters to handle. You can add a custom definition with this:

```php
$configurator->MediaEmbed->add(
	'switch',
	[
		'host'    => 'tube.switch.ch',
		'extract' => '#/(?:embed|videos)/(?<id>\\w+)#',
		'iframe'  => ['src' => 'https://tube.switch.ch/embed/{@id}']
	]
);
```

https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/
