### ISSUE TITLE
Making use of lite-youtube-embed

### ISSUE THREAD

**Issue by iamdarkle** [s9e/TextFormatter#198]
Looking for some ways to improve performance on my site I checked this post from web.dev (https://web.dev/iframe-lazy-loading/)

Where they recommend using YouTube lite component (https://github.com/paulirish/lite-youtube-embed), I took a look at it and the improvement is about 224× faster, it sounds pretty absurd but it is... Would it be possible to implement this for youtube MediaEmbed?

**Comment by JoshyPHP** [comment]
Yes, but that's something you need to implement at the site level. You'd need to load YouTube Lite (or any other lazy loading implementation) in your page and [modify the YouTube template](https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Change_template/) accordingly.

Note that iframes lazy loading is already enabled at the browser level. I'd be *particularly* surprised if YouTube Lite made any page 200x faster.

**Comment by iamdarkle** [comment]
Obviously not the site load but the individual youtube load, in this example you can see that it goes from 1.7MB -> 5.65 s to 40.1KB -> 378 ms so it is quite significant.

![](https://user-images.githubusercontent.com/39191/68095562-5d2ba380-fe5f-11e9-8b5f-18f451b0716d.png)
![](https://user-images.githubusercontent.com/39191/68095563-5d2ba380-fe5f-11e9-8f9a-f5c4a774cd56.png)

Especially in my case where there are at least 10 videos on the homepage the improvement I could have with this is huge both in speed and data saving on mobile devices.

Unfortunately the `loading="lazy"` with youtube is practically useless since in the initial loading it also performs the rest of the requests whether or not it is on screen... apart from the fact that it doesn't affect the data consumption, which is very high at 1.7 MB - 2.1 MB per video, the site is a mobile data consumption machine.

In case you prefer not to implement this from here, would you accept this small commissioned work to add this to Flarum? If so, do you have somewhere we can talk?

Feel free to close this issue if you consider it appropriate.

**Comment by JoshyPHP** [comment]
Sure, send me a mail to s9e.dev`@`gmail.com with your budget range and I'll get back to you shortly. I already have an interest in proxy players but I need to figure out how it would integrate with Flarum.

I have a page with a couple of demo if you're curious: https://s9e.github.io/players/

**Comment by iamdarkle** [comment]
Great, I'll send you an email.
