### ISSUE TITLE
Add zingmp3 and nhaccuatui support

### ISSUE THREAD

**Issue by bachmx** [s9e/TextFormatter#199]
These are very popular music site in Vietnam. I post some link here:

https://zingmp3.vn/bai-hat/Trai-dat-tron/IWAUZCIB.html

https://www.nhaccuatui.com/bai-hat/qua-o-cua-thoi-gian-quai-vat-ti-hon.D1TJs1IfTd.html

**Comment by JoshyPHP** [comment]
I don't think that would be a good fit to be bundled by default. Your best option is to create a media site for yourself using the provided API.

https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/
