### ISSUE TITLE
Add Support For Odysee

### ISSUE THREAD

**Issue by mueenulit** [s9e/TextFormatter#200]
Hi, 
Currently TextFormatter Doesn't have support for Odysee to Embed Videos Automatically from Link ..

Please Add Support for Odysee.com..

**Comment by JoshyPHP** [comment]
It does. I assume you're using an outdated version of something. If not, please post the URL you tried to embed with the exact description on how you use the library.

https://github.com/s9e/TextFormatter/blob/master/src/Plugins/MediaEmbed/Configurator/sites/odysee.xml
