### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by dchubad** [s9e/TextFormatter#201]
Hi, I am having troubles with the installation. 
Is there a step by step guide to installing this? I have no idea how to instal using the composer.json file? I'd like to give this package a try and see if it will work on my site. Thanks

**Comment by JoshyPHP** [comment]
There's really only one step, you have to have [Composer](https://getcomposer.org/) installed and run `composer require s9e/text-formatter` in your project directory. Then you have to load Composer's autoloader normally and you can execute any of the examples.

You can also clone the repository, run `composer install` to install the dependencies, then run the examples in the `docs` directory.

**Comment by dchubad** [comment]
how do you install composer?

**Comment by dchubad** [comment]
It's ok I just copied the whole directory to my root directory and it worked, thanks

**Comment by dchubad** [comment]
ok back again, installed composer (after googling).
I extracted the package to htdocs/s9e where the composer.json file is. In the composer command window I typed: composer require s9e/text-formatter and this is the message I get...

c:\xampp\htdocs\s9e>composer require s9e/text-formatter
Using version ^2.11 for s9e/text-formatter
Root package 's9e/text-formatter' cannot require itself in its composer.json

c:\xampp\htdocs\s9e>

Any help would be much appreciated, I seem to be struggling with this somewhat.

**Comment by JoshyPHP** [comment]
If you've cloned this repository then you'd need to run `composer install` instead. If you want to experiment, I recommend cloning [this repository](https://github.com/s9e/MyProject) instead. You can use it via your webserver through the `www/index.php` file.

**Comment by dchubad** [comment]
I did run that command and it installed all the dependencies.

16 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
40 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> php scripts/patchReadme.php
Could not open input file: scripts/patchReadme.php
Script php scripts/patchReadme.php handling the post-update-cmd event returned with error code 1

c:\xampp\htdocs\s9e>

I do have a question though which I find strange, when you download TextFormatter-master.zip from here and extract the file to say my htdocs folder (root dir) it looks like this htdocs/TextFormatter-master/src but in my test page which is www.xxxxx.com/test.php it says to use this use s9e\TextFormatter\Bundles\Forum as TextFormatter; Using this causes an error on my page which is as follows:
Fatal error: Uncaught Error: Class "s9e\src\Bundles\Fatdown" not found in C:\xampp\htdocs\test.php:62 Stack trace: #0 {main} thrown in C:\xampp\htdocs\test.php on line 62

**Comment by JoshyPHP** [comment]
Forget about everything, delete everything and start anew. Note that there's a difference between a git clone and downloading an archive from GitHub. It won't make a difference here but it's still important enough to note.

Download the [MyProject archive](https://github.com/s9e/MyProject/archive/refs/heads/master.zip), unzip it wherever then run `composer install` in its directory. It should give you a working `www/index.php` page.

**Comment by dchubad** [comment]
I think a lot of the problem for me is knowing the directory tree and the named directories. I have been working at this since 6am and it is now 19:08pm so I will give it a rest for the night but thanks anyway for your help
