### ISSUE TITLE
Add PeerTube

### ISSUE THREAD

**Issue by valsha** [s9e/TextFormatter#204]
Good day, can you add support PeerTube?
https://docs.joinpeertube.org/api-embed-player
https://joinpeertube.org/
Thank you.

**Comment by JoshyPHP** [comment]
PeerTube is a software rather than a media provider. You'd have to create [a custom media site](https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/) for each implementation you want to support.
