### ISSUE TITLE
Rutube doesn't work

### ISSUE THREAD

**Issue by rxu** [s9e/TextFormatter#207]
Something has been changed in Rutube embed links (not sure if adding `[a-z]` to ids is the only change though), so links like `https://rutube.ru/play/embed/827e6fd0929384115958df8addc03a43` yield error:

![image](https://user-images.githubusercontent.com/212322/209963553-f9e179b5-5554-4e65-8d83-f888484f7db8.png)

Old link to the same video with old (numeric) id `http://rutube.ru/play/embed/11203928` still works fine.

phpBB 3.3.9 / Mediaembed 2.11.5.
Same issue on the latest 2.12.3.

**Comment by JoshyPHP** [comment]
Rutube used to have two sets of IDs, the numeric `id` used for the embed page and a 32-char alphanumeric `vid` used in URLs. It seems that they are now commingling them and using them indifferently. I'm going to update the site's definition to identify both of them as `id`, which seems to fix it in every live URL I could find.
