### ISSUE TITLE
[Markdown] Reference-style links not working in posts

### ISSUE THREAD

**Issue by fuzzmz** [s9e/TextFormatter#21]
Reference-style Markdown links aren't working.

In the following example the first markdown link (`Google`) doesn't get turned into a hyperlink once the post is made, while the second one (`this one`) works as expected:

```markdown
This [Google][1] link doesn't work while [this one](https://google.com "Google") does.
    [1]: https://google.com "Google"
```

Ties to flarum/core/issues/630

**Comment by JoshyPHP** [comment]
I replied on the other page but I'll leave a comment here as well. I think that the syntax for reference links is cruft and implementing it would make the library worse. I don't think there's a use case for it in modern applications.

**Comment by fuzzmz** [comment]
I have nothing against not having this feature. I only came across it as I've been toying with integrating @flarum as a commenting system for a @pelican powered blog, and was using the article summary as forum post contents, which in my case happened to use reference-style links.

**Comment by JoshyPHP** [comment]
I've thought about it and decided to implement reference links and images. I don't think anyone will really use it but I was able to implement it without adding too much code and without any impact on the runtime performance. The syntax is consistent with the original Markdown, if a little bit more flexible.

For reference, this is the new supported markup: [*(compare it on Babelmark 2)*](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+%5Blabel%5D%0A*+%5Btext%5D%5Blabel%5D%0A*+!%5Blabel%5D%0A*+!%5Btext%5D%5Blabel%5D%0A*+%5B!%5Blabel%5D%5D%5Blabel%5D%0A%0A%5Blabel%5D%3A+http%3A%2F%2Fexample.org%2Fimg.png+%22Title%22)

```
* [label]
* [text][label]
* ![label]
* ![text][label]
* ![[label]][label]

[label]: http://example.org/img.png "Title"
```

**Comment by fuzzmz** [comment]
Thanks @JoshyPHP! :+1:
