### ISSUE TITLE
How to support .mov video?

### ISSUE THREAD

**Issue by bryanyang0528** [s9e/TextFormatter#210]
I saw the source code of autovideo did not include the `.mov` file. 
Is it possible to support .mov?

The HTML tag would be like this:
```
<video width="400" controls autoplay>
    <source src="D:/mov1.mov" type="video/mp4">
</video>
```
Thank you

**Comment by JoshyPHP** [comment]
I'm going to add `.mov` to the list of allowed extensions in the Autovideo plugin. The correct MIME type is `video/quicktime` but the default template does not specify the type and leaves that to the server/browser.
