### ISSUE TITLE
html formatted email phpbb

### ISSUE THREAD

**Issue by FuzzyThor** [s9e/TextFormatter#216]
How can i create a custom html template so emails are styled when using phpbb

can i add my html code to this

`		// Set the default template
		$tag->template = '<a href="mailto:{@' . $this->attrName . '}"><xsl:apply-templates/></a>';`

**Comment by FuzzyThor** [comment]
These are the text files that phpbb uses when sending email notifications.
![Screenshot 2023-04-14 122928](https://user-images.githubusercontent.com/3608771/232138679-511b3805-98d7-45a9-8e9a-f0f21bcc4b4f.png)
![Screenshot 2023-04-14 122531](https://user-images.githubusercontent.com/3608771/232138693-f1001b8a-c406-4196-a32d-980ee101e4f6.png)
This is what it looks like in my email
![plain](https://user-images.githubusercontent.com/3608771/232139013-64b73a74-4356-4240-ba26-c7ec8814f62d.png)
I have tried adding html to the txt files to style how the emails should look. Like banner image and background other than just the plain white background black text. 
I am hopping to style the emails that from from phpbb to look like this
![email_template](https://user-images.githubusercontent.com/3608771/232139396-08a0ea05-96d9-41b7-ba31-bfe6405eb9bd.png)
I am not sure how to achieve my desired outcome as adding the html to the txt files in the email template folder didn't seem to work. I figured it had seomthing to do with the system handling the text formatter.

**Comment by JoshyPHP** [comment]
Oh, then you're in the wrong place. I don't think that emails sent by phpBB go through this library at all. You need to post the same thing to phpBB's support forums, ask them whether it's possible to use HTML in emails sent *by* phpBB. I don't think that's the case but it won't hurt to ask.

**Comment by FuzzyThor** [comment]
I figured it out with hours of digging
