### ISSUE TITLE
Did  Instagram videos currently play  properly?

### ISSUE THREAD

**Issue by efast1568** [s9e/TextFormatter#219]
I am experiencing issues with playing videos on Instagram on both Flarum and Waterhole  . Previously, they were playing normally.

https://waterhole.subarist.net/posts/94853-mediaembed-test/comments/573906

**Comment by JoshyPHP** [comment]
Instagram slightly changed the way they communicate the size of their embeds and the new message wasn't recognized. I have updated the hosted iframe in https://github.com/s9e/s9e.github.io/commit/5fb3f7247297264dc47677236e7acc15abfa62a8 and it should work normally now.
