### ISSUE TITLE
Array template parameters

### ISSUE THREAD

**Issue by rxu** [s9e/TextFormatter#231]
Is it technically possible to add array template parameters? So that one would be able to do something like (no idea if it's valid though)
```xml
<xsl:for-each select="$GROUPS">
    <xsl:if test="$GROUPS=1">{TEXT}</xsl:if>
</xsl:for-each>
```

**Comment by JoshyPHP** [comment]
No, template parameters are really only strings. The renderer will accept any types but it will cast them to `string`.

XSLT1 doesn't have arrays either, the closest it has are nodes but you need [EXSLT's str:split()](https://developer.mozilla.org/en-US/docs/Web/EXSLT/str/split) to create your own. Either way, your next issue would be that [the PHP renderer](https://s9etextformatter.readthedocs.io/Internals/PHP_renderer/#php-renderer-limitations) doesn't support `xsl:for-each`. I didn't list the exact set of XSLT that is supported but you can look up the [DisallowUncompilableXSL](https://github.com/s9e/TextFormatter/blob/master/src/Configurator/TemplateChecks/DisallowUncompilableXSL.php) class for reference.

In general, the simplest way to check whether a numeric value is in a set is to concat the set's values into a string, using a delimiter to eliminate false positives. For example:

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->rendering->engine = 'PHP';

$configurator->BBCodes->addCustom(
	'[showgroups]',
	'<xsl:if test="contains($GROUPS, \' 1 \')"><p>1 was found</p></xsl:if>
	<xsl:if test="contains($GROUPS, \' 2 \')"><p>2 was found</p></xsl:if>
	<xsl:if test="contains($GROUPS, \' 11 \')"><p>11 was found</p></xsl:if>
	<xsl:if test="contains($GROUPS, \' 22 \')"><p>22 was found</p></xsl:if>'
);

extract($configurator->finalize());

$renderer->setParameter('GROUPS', ' 1 2 3 4 11 ');

$text = '[showgroups]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<p>1 was found</p><p>2 was found</p><p>11 was found</p>
```

**Comment by rxu** [comment]
Thanks a lot for the hint, that actually works like a charm.
