### ISSUE TITLE
Adding custom site with template fails

### ISSUE THREAD

**Issue by xawiers** [s9e/TextFormatter#24]
Adding custom site with custom template (not iframe, not flash) fails - template is not generated because template builder has only 3 template types: choose flash and iframe.

**Comment by JoshyPHP** [comment]
You don't have to specify a template when you add a site. The `add()` method returns the tag that corresponds to the newly-added site, you can modify its template after the fact. For example:

```php
$tag = $configurator->MediaEmbed->add(
    'youtube',
    [
        'host'    => 'youtube.com',
        'extract' => "!youtube\\.com/watch\\?v=(?'id'[-\\w]+)!"
    ]
);

$tag->template = '...';
```

**Comment by xawiers** [comment]
Actually You do it wrong: manual says that template must be defined in add method parameter. I do as manual says and can't get the result.
http://s9etextformatter.readthedocs.org/Plugins/MediaEmbed/Add_custom/
Either fix manual, either fix code. One or another way it's a bug.
Of course better to add support for template parameter - then its easier to use in array config or mass config using arrays.

**Comment by JoshyPHP** [comment]
Support for custom templates in the MediaEmbed configurator was removed in 3f5e4991220d9eba270e3dbe46e98be0bf24d353. This is just a leftover line that was missed at the time. I updated the doc accordingly.

**Comment by xawiers** [comment]
Ok thanks.
