### ISSUE TITLE
Attempt using 'dark' mode has no effect

### ISSUE THREAD

**Issue by rxu** [s9e/TextFormatter#242]
Probably misusing the feature, but the story is the following.
text-formatter version: 2.11.5 (the highest possible for phpBB3).
`'MEDIAEMBED_THEME' => 'dark'` has been added via renderer setup.
Despite that, it doesn't seem to make any effect.
Random example link: `https://www.instagram.com/p/CecpgytO2Cr` is rendered still in light style. `iframe` tag is the following:
```html
<iframe data-s9e-mediaembed="instagram" allowfullscreen="" loading="lazy" onload="var c=new MessageChannel;c.port1.onmessage=function(e){style.height=e.data+'px'};contentWindow.postMessage('s9e:init','https://s9e.github.io',[c.port2])" scrolling="no" style="border: 0px; height: 1085px; max-width: 540px; width: 100%;" src="https://s9e.github.io/iframe/2/instagram.min.html#CecpgytO2Cr#theme=dark"></iframe>
```

`theme=dark` anchor is there though. At the same time, phpBB cache file (like `s9e_renderer_b7ca6995b823aca4a93e8e3adc5dbc41b309136a.php`) still contains `'MEDIAEMBED_THEME'=>''` in the list.

Not sure where to dig deeper to debug this. Thanks.

**Comment by JoshyPHP** [comment]
Instagram embeds used to have a `dark` theme but it was left in disrepair as the default style received updates. In the end, it was unreadable and it looks like they've removed it now. I left the theme selector in the site's definition in case they reinstate it.
