### ISSUE TITLE
Changing arrow-up symbol in phpBB BBcode template results in error

### ISSUE THREAD

**Issue by C1n** [s9e/TextFormatter#25]
I wanted to choose a different symbol for the link to original post so I changed the arrow-up symbol in the BBcode.html inside prosilvers template (from &#8593; to &#8921;) but I then get the following error: 

[phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Configurator.php on line 7414: DOMXPath::evaluate(): Undefined namespace prefix
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Configurator.php on line 7414: DOMXPath::evaluate(): Invalid expression
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Configurator.php on line 7414: DOMXPath::evaluate(): Undefined namespace prefix
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Configurator.php on line 7414: DOMXPath::evaluate(): Invalid expression
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Configurator.php on line 7414: DOMXPath::evaluate(): Undefined namespace prefix
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Configurator.php on line 7414: DOMXPath::evaluate(): Invalid expression
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Configurator.php on line 7500: DOMXPath::query(): Undefined namespace prefix
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Configurator.php on line 7500: DOMXPath::query(): Invalid expression
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Configurator.php on line 7500: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Configurator.php on line 7410: DOMXPath::evaluate(): Undefined namespace prefix
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Configurator.php on line 7410: DOMXPath::evaluate(): Invalid expression

Fatal error: Uncaught Error: Call to a member function removeChild() on null in .../phpBB/vendor/s9e/text-formatter/src/Configurator.php:7475 Stack trace: #0 .../phpBB/vendor/s9e/text-formatter/src/Configurator.php(7380): s9e\TextFormatter\Configurator\TemplateNormalizations\OptimizeChoose->optimizeChooseElement() #1 .../phpBB/vendor/s9e/text-formatter/src/Configurator.php(5100): s9e\TextFormatter\Configurator\TemplateNormalizations\OptimizeChoose->normalize(Object(DOMElement)) #2 .../phpBB/vendor/s9e/text-formatter/src/Configurator.php(2673): s9e\TextFormatter\Configurator\TemplateNormalizer->normalizeTemplate('<blockquote><xs...') #3 .../phpBB/vendor/s9e/text-formatter/src/Configurator.php(5086): s9e\TextFormatter\Configurator\Items\Template->normalize(Object(s9e\TextFo in .../phpBB/vendor/s9e/text-formatter/src/Configurator.php on line 7475

**Comment by JoshyPHP** [comment]
How did you change the template?

**Comment by C1n** [comment]
Download via FTP, change with notepad++, reupload = error.

I have included the good and bad version.

[BBcode.html.zip](https://github.com/s9e/TextFormatter/files/127285/BBcode.html.zip)

**Comment by JoshyPHP** [comment]
I can't reproduce it locally. Try updating your version of the library by running `composer up s9e/text-formatter` in your phpBB directory or by manually replacing [this file](https://github.com/s9e/TextFormatter/blob/release/php5.3/src/Configurator.php).

What other styles do you have installed? Try disabling it and purging the cache.

**Comment by C1n** [comment]
The update worked, thanks!

**Comment by JoshyPHP** [comment]
Cool. I guess that was just another side-effect of the bug you reported the other day.

**Comment by C1n** [comment]
I tested some more and I finally figured out what the problem was: 

I have a custom style which I installed with prosilver as a parent. When I edit the bbcode.html template from my custom style without doing the exact same change in the prosilver bbcode.html I produce the aforementioned error. 

The update didn't resolve the problem, I just deinstalled the styles, but when I  reconfigured prosilver as a parent, the issue reappeared. I think you can produce it yourself by doing the exact same thing I did. 

I resolved it by editing bbcode.html of both styles with the same change. This fixed it for me, but maybe you want to look into this further.

**Comment by JoshyPHP** [comment]
Can you send me the other bbcode.html file please? Or you can just copy/paste the quote template here in a code block.

**Comment by C1n** [comment]
[bbcodes.zip](https://github.com/s9e/TextFormatter/files/129912/bbcodes.zip)

**Comment by JoshyPHP** [comment]
I have identified the issue and will publish a fix shortly. Thanks for the report.

**Comment by C1n** [comment]
all right, no prob!
