### ISSUE TITLE
Cannot access protected property s9e\TextFormatter\Plugins\Autolink\Configurator::$matchWww

### ISSUE THREAD

**Issue by xawiers** [s9e/TextFormatter#28]
Code:

    $configurator = new \s9e\TextFormatter\Configurator;
    $configurator->rootRules->enableAutoLineBreaks();
    $configurator->plugins->load('Litedown');
    $configurator->plugins->load('Autoemail');
    $configurator->Autolink->matchWww = true;

gives error:
Cannot access protected property s9e\TextFormatter\Plugins\Autolink\Configurator::$matchWww
PHP 5.6.20

Official documentation: 
http://s9etextformatter.readthedocs.org/Plugins/Autolink/Synopsis/

**Comment by JoshyPHP** [comment]
The doc's based on the master branch. In versions older than 0.5.0 you need to set it at loading time.

```php
$configurator->plugins->load('Autolink', ['matchWww' => true]);
```
