### ISSUE TITLE
Using TextFormatter in MyBB 2

### ISSUE THREAD

**Issue by xaoseric** [s9e/TextFormatter#29]
Hi, we have discussed using your package for the parser of mybb 2 instead of reimplementing the wheel. Would you have any objection to us using it? 

https://github.com/mybb/mybb2/issues/193
https://github.com/mybb/Parser

**Comment by JoshyPHP** [comment]
Objection? Of course not, I'd love it! :grinning: Actually I suggested it a few years ago [on MyBB's board](http://community.mybb.com/thread-141772.html). I'm going to comment on the issue you linked as soon as I can. Feel free to tag me in any related discussion I missed, thanks.
