### ISSUE TITLE
emoji path

### ISSUE THREAD

**Issue by Lafriakh** [s9e/TextFormatter#30]
is it possible to set emoji path to use different emojis, like apple, google...

**Comment by JoshyPHP** [comment]
You can use [either EmojiOne or Twemoji](http://s9etextformatter.readthedocs.io/Plugins/Emoji/Synopsis/). I'm not aware of publicly-accessible imagesets for Apple's or Google's emoji.

If you host the images on your own, you can modify the template to point to your own files.

```php
echo $configurator->Emoji->getTag()->template;
```

**Comment by Lafriakh** [comment]
how to change the value of template?

**Comment by JoshyPHP** [comment]
You can access it as a string, or you can [modify it through DOM manipulation](http://s9etextformatter.readthedocs.io/Templating/Modify_a_template/).

**Comment by Lafriakh** [comment]
Thank, but it wood be nice to add this feature.

**Comment by JoshyPHP** [comment]
I'll consider adding an option to set the URL but the use case seems extremely narrow. Also, each emoji set has different rules for their filenames:

* [Twemoji](https://github.com/twitter/twemoji/tree/gh-pages/36x36)'s filenames are lowercase without leading zeroes, e.g. [23-20e3.png](https://github.com/twitter/twemoji/blob/gh-pages/36x36/23-20e3.png)
* [gemoji](https://github.com/github/gemoji/tree/master/images/emoji/unicode)'s filenames are lowercase with leading zeroes, e.g. [0023-20e3.png](https://github.com/github/gemoji/blob/master/images/emoji/unicode/0023-20e3.png)
* Emoji One's filenames used to be uppercase with leading zeroes, e.g. 0023-20E3.svg and now they're lowercase with leading zeroes.

**Comment by Lafriakh** [comment]
i think short name for emojis wood solve this problem
see this: [Emoji Cheat Sheet](http://www.emoji-cheat-sheet.com/)
and there examples in emojione by parse emoji from shortname: [shortnameToImage](http://git.emojione.com/demos/2.2.4/phpshortnametoimage.php)
