### ISSUE TITLE
Suggestion: use Embed library

### ISSUE THREAD

**Issue by oscarotero** [s9e/TextFormatter#32]
Hello.
Just dropping it here: https://github.com/oscarotero/Embed
It's a library to extract info from urls. Maybe you find it interesting to implement into the MediaEmbed and avoid to implement and maintain manually all the sites.

**Comment by JoshyPHP** [comment]
Hi,

That wouldn't work in the context of this library. Most of the processing happens [when the text is parsed then stored as XML](http://s9etextformatter.readthedocs.io/Getting_started/How_it_works/) but the final HTML is generated later. Most libraries don't really fit in that process. If they're used before storage then the HTML or URLs they produce can become stale. If they're used at rendering time, any remote API call such as oEmbed's can significantly delay the page.

What libraries like Embed may be useful for is generating site definitions dynamically, but I've never had time to really look into it.
