### ISSUE TITLE
Configurator export should cast key to int

### ISSUE THREAD

**Issue by marc1706** [s9e/TextFormatter#33]
The export() method relies on being able to add `1` to the value of `$k`:
https://github.com/s9e/TextFormatter/blob/0.5.4/src/Configurator.php#L3575

This is however causing issues with PHP 7.1:
```
PHP Warning:  A non-numeric value encountered in /home/travis/build/phpbb/phpbb/phpBB/vendor/s9e/text-formatter/src/Configurator.php on line 3575
```

A simple fix for this would be to cast the key to int.

**Comment by JoshyPHP** [comment]
I'm going to look into it. Actually I suspect the whole `$naturalKey = $k + 1;` is incorrect so I'll probably end up replacing the algorithm altogether.

**Comment by marc1706** [comment]
Can you give me a heads up when you create a new tag so we can incorporate this into our composer.json? Thanks.

**Comment by JoshyPHP** [comment]
Sure thing.

**Comment by JoshyPHP** [comment]
@marc1706 I've just tagged [v0.6.0](https://github.com/s9e/TextFormatter/releases/tag/0.6.0), which contains the fix for this issue. There's a couple of API changes but nothing that phpBB uses AFAIK.

I've added PHP 7.1 to my build matrix so I don't expect any new 7.1-related issues to crop up.

**Comment by marc1706** [comment]
Ok, thanks for the update. Will prepare a PR to update the text formatter to confirm there are no breaking changes in regards to phpBB.
