### ISSUE TITLE
feature request: crunchyroll

### ISSUE THREAD

**Issue by terabin** [s9e/TextFormatter#38]
Well, crunchyroll is a official anime stream website, and this type of content cannot can be shared in many countries. (legally)

So, maybe is a good idead include this site.

http://www.crunchyroll.com/

**Comment by JoshyPHP** [comment]
If you post the kind of URL that would be embedded I'll consider it. Last time I checked (two years ago) only Crunchyroll affiliates were allowed to embed their videos.

**Comment by terabin** [comment]
You're right, unfortunately they canceled the affiliate program and promised a "new" and more accessible.

We can only wait.
