### ISSUE TITLE
MediaEmbed: add site names to site definitions

### ISSUE THREAD

**Issue by rxu** [s9e/TextFormatter#45]
In <a href="https://github.com/phpbb-extensions/mediaembed">phpBB Mediaembed extension</a> for phpBB 3.2, there's an option to enable/disable sites in ACP.
It would look nicer to have site names instead of site IDs in the list.
Probably by adding some key like 'sitename' to the definitions if possible.

**Comment by VSEphpbb** [comment]
A method similar to getIds(), i.e.: getSites() or something, would be helpful in being able to spit out lists of the supported sites, similar to how they are shown in the docs at http://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Sites/

**Comment by JoshyPHP** [comment]
Ok, I'll think about it.

**Comment by JoshyPHP** [comment]
Starting with v0.8.0 you should be able to iterate over the default sites, access them as an array and pull the site's name. There's also an optional field called `tags` that contains an array of strings that can be used to categorize a site. 

```php
$configurator = new s9e\TextFormatter\Configurator;
foreach ($configurator->MediaEmbed->defaultSites as $siteId => $siteConfig)
{
	printf("%10s %s\n", $siteId, $siteConfig['name']);
}
```
```
   abcnews ABC News
    amazon Amazon Product
 audioboom audioBoom
 audiomack Audiomack
  bandcamp Bandcamp
         ...
```

**Comment by VSEphpbb** [comment]
So will this break backwards compatible with the current way?

**Comment by JoshyPHP** [comment]
If you use the `s9e\TextFormatter\Plugins\MediaEmbed\Configurator\SiteDefinitionProvider` interface, yes. You'll have to replace it with the array notation.

http://s9etextformatter.readthedocs.io/Internals/API_changes/#080

**Comment by VSEphpbb** [comment]
I meant, more specifically, to this type of usage: https://github.com/phpbb-extensions/mediaembed/blob/master/event/main_listener.php#L70-L72

**Comment by VSEphpbb** [comment]
Can you please, possibly, keep something to maintain BC if possible? This will be a huge headache for the "extension" adding this to phpBB if they ever upgrade phpBB's text formatter dep to 0.8.

**Comment by JoshyPHP** [comment]
`getIds()` was part of the `SiteDefinitionProvider` interface so yes, that won't work in future versions.

That interface was not good, I'd rather not add a BC layer for it. Until the dependency in phpBB's composer.json is updated, you can test whether `$configurator->MediaEmbed->defaultSites` implements the interface or is iterable and use whichever is available.

**Comment by VSEphpbb** [comment]
OK then. When do you think you'll release 0.8? The phpBB dev's will like to try to get Text Formatter 0.8 into their 3.2.x release, so we can do this properly (without "hacks"). Thanks.

**Comment by JoshyPHP** [comment]
Probably next week-end, or potentially the one after. If there's a 3.2 release planned before that you can ping me and I'll release mine earlier.
