### ISSUE TITLE
Issues with strpos with 0.8.0

### ISSUE THREAD

**Issue by Nicofuma** [s9e/TextFormatter#46]
```
PHP Warning:  strpos() expects parameter 1 to be string, object given in /home/travis/build/phpbb/phpbb/phpBB/vendor/s9e/text-formatter/src/Configurator.php on line 2582
PHP Warning:  strpos() expects parameter 1 to be string, object given in /home/travis/build/phpbb/phpbb/phpBB/vendor/s9e/text-formatter/src/Configurator.php on line 2584
```
etc...

https://travis-ci.org/phpbb/phpbb/jobs/166266901

**Comment by JoshyPHP** [comment]
That's an interesting one. 😅 I'll publish a hotfix for it tomorrow.

**Comment by JoshyPHP** [comment]
[0.8.1 is out](https://github.com/s9e/TextFormatter/releases/tag/0.8.1), it contains a fix for the issue triggered in phpBB and a type check as a proactive measure against future issues.

**Comment by Nicofuma** [comment]
thanks
