### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by Remo** [s9e/TextFormatter#47]
Is there a way to show tables? Something like this:

https://www.bbcode.org/examples/?id=14

UPDATE: An integrate of http://parsedown.org/ might be even better as the table syntax of markdown is much easier to type.

**Comment by JoshyPHP** [comment]
You can add BBCodes for it, or enable the relevant HTML elements. I'm going to add some BBCodes to the default repository.

Currently I don't plan on adding the ASCII-style tables that you can see in some flavours of Markdown. The syntax seems hard to implement properly.
