### ISSUE TITLE
Contradiction in the documentation

### ISSUE THREAD

**Issue by brunoais** [s9e/TextFormatter#5]
At: https://github.com/s9e/TextFormatter/blob/master/docs/Rules.md
On: defaultChildRule
In:
>If defaultChildRule is set to 'deny', all tags that are not targeted by an allowChild rule will be denied. By default, defaultChildRule is set to 'deny', which means that all tags are allowed as children unless they are targeted by a denyChild rule.

The explanation in both sentences contradicts itself. Did you mean that defaultChildRule defaults to `allow` instead of `deny`

**Comment by s9e** [comment]
You're correct. Thanks for pointing that out.
