### ISSUE TITLE
Parse BBcode tags with uid

### ISSUE THREAD

**Issue by sirlancelot** [s9e/TextFormatter#52]
I'm migrating a forum for a client using an old version of phpBB. All of the posts are written with some sort of "uid" embedded in each bbcode tag which is unique for every post. It looks like this:

> [u:d73bfb9507]Standard Edition[/u:d73bfb9507]
> [size=18:d73bfb9507]Links[/size:d73bfb9507]
> [quote:160984a301="Username"]This is an example post in your phpBB 2 installation. You may delete this post, this topic and even this forum if you like since everything seems to be working![/quote:160984a301]

I pasted this snippet in to the [demo](http://s9e.github.io/TextFormatter/demo.html) and it doesn't appear to recognize this structure. If I remove the `:d73bfb9507` bit from each tag it works except for the size tag.

**Comment by JoshyPHP** [comment]
The BBCodes plugin supports numeric identifiers (e.g. `[u:123]...[/u:123]`) to uniquely pair BBCode tags together but not alphanumeric identifier.

phpBB does more than adding those identifiers though, it also adds HTML comments and `<img>` elements, encodes some characters as HTML entities and adds "magic" BBCodes in some places. I recommend using phpBB's `decode_message()` function to revert the text to its original form, without the UIDs and those other things.
