### ISSUE TITLE
FancyPants configuration

### ISSUE THREAD

**Issue by RikSomers** [s9e/TextFormatter#55]
Hi,

I would like to be able to enable / disable certain parts of the fancypants plugin. Is this possible?

For example, I want to be able to parse (TM) and (C), but not conver quote pairs to fancy quotes. 

My suggested fix for this would be to allow additional configuration like this for example:
`$configurator->FancyPants->matchQuotes = true;`

**Comment by RikSomers** [comment]
If you'd like, I could create a PR for this somewhere in the next couple days btw, unless you're fine with changing it yourself.

**Comment by JoshyPHP** [comment]
That won't be necessary. I'm not opposed to the idea of toggling some of the replacements but I'm not sure I want to add 8 configuration options with 8 ifs. I'm going to need to mull it over for a little while.

**Comment by RikSomers** [comment]
I can imagine. 

To be honest the only thing users of my site would probably really use are the (C) and (TM) and maybe the dashes and ellipses which I might just be better of using the PREG replacement plugin for.

**Comment by JoshyPHP** [comment]
After some consideration I went with 5 groups of replacements, listed in the docs here: http://s9etextformatter.readthedocs.io/Plugins/FancyPants/Synopsis/#how-to-disable-a-pass

**Comment by RikSomers** [comment]
Amazing! Thanks :)
