### ISSUE TITLE
Noparse inside noparse not matched correctly

### ISSUE THREAD

**Issue by RikSomers** [s9e/TextFormatter#56]
Hi!

The following:

```
[noparse]
[noparse][/noparse]
[/noparse]
```

Will produce:
```
[noparse]
[/noparse]
```

When I would expect the output to be without whitespaces like:
```
[noparse][/noparse]
```

The XML (after parsing) is as follows:
``` 
<r><NOPARSE><s>[ignore]</s><br/>
    [ignore]<e>[/ignore]</e></NOPARSE><br/>
    [/ignore]</r>
```

Which seems to me is totally incorrect?

The usage / template I use are `[NOPARSE #ignoreTags=true]{TEXT}[/NOPARSE]`(usage) and `{TEXT}`(template)

Is the behaviour intended and am I missing something, or is this a bug?

Sincerely
Rik

**Comment by JoshyPHP** [comment]
It's intended. The second `[noparse]` tag is ignored. You can [uniquely pair BBCodes](http://s9etextformatter.readthedocs.io/Plugins/BBCodes/Synopsis/) by assigning them a number. For example:

```
[noparse:123]
[noparse][/noparse]
[/noparse:123]
```
```xml
<r><NOPARSE><s>[noparse:123]</s>
[noparse][/noparse]
<e>[/noparse:123]</e></NOPARSE></r>
```

**Comment by RikSomers** [comment]
But (for example) on a forum you can't really force people to use the colon-syntax to pair them. So to me, this still looks like unintended behaviour. 

Then again, this really is an edge-case that should not come up that much

**Comment by JoshyPHP** [comment]
It's unambiguous, which is a valuable property when it comes to markup languages. There isn't really a good way to balance tags and also ignore them at the same time. If it worked the other way around then `[noparse][noparse][/noparse]` would become another edge-ier case, and so on. With no solid and obvious solution, I chose the unambiguous way to treat this markup.

**Comment by RikSomers** [comment]
Yeah, it only really happens with this no-parse case. You would need something like a stack-based BBcode parser to really be able to match outer tags with eachother, which isn't what this package tries to achieve.

I'll close this issue then.

**Comment by JoshyPHP** [comment]
Well, the parser does use a stack but it's purposefully inaccessible from plugins. A list of open tags is [available to filters](http://s9etextformatter.readthedocs.io/Filters/Callback_signature/) but it's read-only. The renderer has the whole DOM at its disposition so it would be possible to treat `[noparse]` as a normal tag that does *not* ignore tags but only allows itself as a child. The first level of `[noparse]` wouldn't render its own markup but deeper levels would. It doesn't solve `[noparse][noparse][/noparse]` though.

Here's an example purely for educational value, I don't recommend anyone uses it.

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addCustom(
	'[NOPARSE #defaultChildRule=deny #allowChild=NOPARSE]{TEXT}[/NOPARSE]',
	'<xsl:choose>
		<xsl:when test="parent::NOPARSE"><xsl:value-of select="."/></xsl:when>
		<xsl:otherwise><xsl:apply-templates/></xsl:otherwise>
	</xsl:choose>'
);

extract($configurator->finalize());

// Instruct the renderer not to remove any meta elements
$renderer->metaElementsRegexp = '((?!))';

$text = '[noparse][noparse][/noparse][/noparse]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$xml\n$html\n");
```
```xml
<r><NOPARSE><s>[noparse]</s><NOPARSE><s>[noparse]</s><e>[/noparse]</e></NOPARSE><e>[/noparse]</e></NOPARSE></r>
```
```
[noparse][/noparse]
```
