### ISSUE TITLE
Markdown quote levels

### ISSUE THREAD

**Issue by 1f7** [s9e/TextFormatter#58]
Hi @JoshyPHP 

today use last (0.9.0) version :)

with test message:
```text
> --- **admin** *[wrote:](/forum/post/30#p30)*
>> --- **admin** *[wrote:](/forum/post/29#p29)*
>>> --- **admin** *[wrote:](/forum/post/26#p26)*
>>>> --- **admin** *[wrote:](/forum/post/26#p26)*
>>>>
>>>>> --- **admin** *[wrote:](/forum/post/25#p25)*
>>>>
>>>>>> --- **odmin** *[wrote:](/forum/post/3#p3)*
>>>>>
>>>>>>1. rewrewerwr
>>>>>>2. wrwrwreer
>>>>>>3. werwerer
>>>>>>4. wrewerrew
>>>>>>5. 234232424
>>>>>>6. dfgdfggfdg  
>>>>>>
>>>>>>> sdfsdfsdfsdf
>>>>>>>> sdfsdfsdfsdf
>>>>>>>>> sdfsdfsdfsdf
>>>>>>
>>>>>>```php
>>>>>>        if ($already_registered) {
>>>>>>            throw new  RunBBException(__('Registration flood'), 429);
>>>>>>        }
>>>>>>```
>>>>>
>>>>>check quote with code
>>>>
>>>>and more 8)
>>
>>and more 8)
>
>
>and more 8)
```
parser return:

```php
array (3)
    0 => "debug" (5)
    1 => "Skipping end tag with no start tag" (34)
    2 => array (1)
        tag => s9e\TextFormatter\Parser\Tag #62f1
            attributes protected => array ()
            cascade protected => array ()
            endTag protected => NULL
            flags protected => 268
            invalid protected => FALSE
            len protected => 0
            name protected => "QUOTE" (5)
            pos protected => 500
            sortPriority protected => 0
            startTag protected => s9e\TextFormatter\Parser\Tag #f0cd { ... }
            type protected => 2
```
if qoutes reduce to one level then no problem  
for information: [SimpleMDE](https://github.com/NextStepWebs/simplemde-markdown-editor) editor i use show this fine

github show fine too.

**Comment by JoshyPHP** [comment]
Debug messages don't necessarily mean there's an error. Is the output incorrect? If so, how? I don't see anything wrong with the output here but there's a lot of text so maybe I'm just not seeing it. If possible, remove anything that isn't directly related to the incorrect output.

**Comment by 1f7** [comment]
![s9e_parser_quote_error](https://cloud.githubusercontent.com/assets/16786165/22117295/e6706ffe-de8c-11e6-9db7-ad36540131aa.png)

if error i escape text. :(
sorry, my mistake error processing.

thanks again for a great parser :1st_place_medal:

**Comment by 1f7** [comment]
btw, which one critical?  
err / warn?
how better work with errors?

**Comment by JoshyPHP** [comment]
There must be something in your configuration that interferes with quote blocks. Please do note that screenshots contain no usable information. Only reproducible code is useful. Here's what I've used to confirm that it works as expected:

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->Litedown;

extract($configurator->finalize());

$text = '> --- **admin** *[wrote:](/forum/post/30#p30)*
>> --- **admin** *[wrote:](/forum/post/29#p29)*
>>> --- **admin** *[wrote:](/forum/post/26#p26)*
>>>> --- **admin** *[wrote:](/forum/post/26#p26)*
>>>>
>>>>> --- **admin** *[wrote:](/forum/post/25#p25)*
>>>>
>>>>>> --- **odmin** *[wrote:](/forum/post/3#p3)*
>>>>>
>>>>>>1. rewrewerwr
>>>>>>2. wrwrwreer
>>>>>>3. werwerer
>>>>>>4. wrewerrew
>>>>>>5. 234232424
>>>>>>6. dfgdfggfdg  
>>>>>>
>>>>>>> sdfsdfsdfsdf
>>>>>>>> sdfsdfsdfsdf
>>>>>>>>> sdfsdfsdfsdf
>>>>>>
>>>>>>```php
>>>>>>        if ($already_registered) {
>>>>>>        }
>>>>>>```
>>>>>
>>>>>check quote with code
>>>>
>>>>and more 8)
>>
>>and more 8)
>
>
>and more 8)';

$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```

**Comment by 1f7** [comment]
in screenshot i show my mistake, not parser.
i recheck quotes to 18 levels and all work fine.

but what i need check in logs, 'err' only, all other can be ignored?

**Comment by JoshyPHP** [comment]
Please understand this: screenshots give no information. Also, I don't understand most of what you're saying. You're talking about "18 levels" but I have no idea what that means. The text you posted shows 9 levels of quotes.

For what it's worth, tags can only be nested 10 times by default. This can be changed during configuration or before parsing. See [Runtime configuration](http://s9etextformatter.readthedocs.io/Getting_started/Runtime_configuration/#limit-the-numbernesting-of-tags).

The types used for errors in the logs are not well-defined. They can help understand why something doesn't work but there is not much difference between errors marked as `err` or `warn`.

**Comment by 1f7** [comment]
now simulate several "Nesting limit exceeded' but result html still valid.
it turns out that I can use all errors as info only, not critical.
sorry if i annoying you, i test only how script work

once more thanks
