### ISSUE TITLE
tapastic support?

### ISSUE THREAD

**Issue by diomed** [s9e/TextFormatter#59]
hello

would it be possible to add support for [tapastic](https://tapastic.com) ?
embedding of comics

**Comment by JoshyPHP** [comment]
Sorry, this site isn't popular enough to warrant maintaining it as part of the default sites. If you want to support embedding content from this site you can create a custom definition for yourself: http://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/
