### ISSUE TITLE
Where is the js BBCode tag parser

### ISSUE THREAD

**Issue by brunoais** [s9e/TextFormatter#6]
Can you please take me to where the BBCode tag parser for the javascript part is?
I'm interested in the parts that parse each specific tag according to its settings and restrictions, not the part that deals with the actual HTML output building, just where it processes the restrictions and decides the actual transformations to use.

**Comment by s9e** [comment]
The BBCodes parser is in [src/Plugins/BBCodes/Parser.js](https://github.com/s9e/TextFormatter/blob/master/src/Plugins/BBCodes/Parser.js). It's a port of Parser.php in the same directory.

Tag rules are applied by the main parser in [`processStartTag()`](https://github.com/s9e/TextFormatter/blob/master/src/Parser.js#L1413).

**Comment by brunoais** [comment]
That was quite useful. Thanks.

**Comment by brunoais** [comment]
Although I could get a lot of content from there... I couldn't get how do you deal with BBCode that follows more interesting approaches such as 1 param into 2 params or 2 params into 1 param like you describe in the CodeMonkey documentation. Where is the js code to do that?

**Comment by s9e** [comment]
They're attribute preprocessors and they're handled in `s9e\TextFormatter\Parser::executeAttributePreprocessors()` or the equivalent JS function. It's an internal data structure though and as such it's subject to change without warning. You should generally not mess with them.

**Comment by brunoais** [comment]
In that case, is there a public API to get the tag parameters?

**Comment by brunoais** [comment]
I just want to get the Regex processing you use to get it up and working ^^. That should do it.

**Comment by s9e** [comment]
All the processing is done in `executeAttributePreprocessors()` but there's no public API for it. Not sure what you're looking for exactly, what are you trying to do?

**Comment by brunoais** [comment]
Ah! Found something here:
