### ISSUE TITLE
Mentions Twitter style @user

### ISSUE THREAD

**Issue by adaur** [s9e/TextFormatter#60]
Hello,

First of all, congratulations for your impressive work.

I am the lead developer of [FeatherBB](http://featherbb.org/), a modern fork of FluxBB, which you know very well thanks to our friend Franz :)

I have integrated your parser to render both markdown and BBcode and it's working well so far.

However, I'd like to add @ user mentions, like here or Twitter. I have not seen an extension for doing such a thing, have I missed something?

I've also tried the following which does not seem to work anymore:

```
// Alias COLOUR to COLOR
        $configurator->BBCodes->add('COLOUR')->tagName = 'COLOR';
```

Thanks!

adaur

**Comment by JoshyPHP** [comment]
You can match mentions' markup using [the Preg plugin](http://s9etextformatter.readthedocs.io/Plugins/Preg/Synopsis/#using-match). You can take a look at Flarum's mentions extension for an example of [how to configure a tag used for user mentions](https://github.com/flarum/flarum-ext-mentions/blob/64d893a4c2ef0335acbaeae924b33e8a5bb82ca4/src/Listener/FormatUserMentions.php#L56-L73). Once the text is parsed you can extract the user IDs from the XML using DOM or using [Utils::getAttributeValues()](http://s9e.github.io/TextFormatter/api/s9e/TextFormatter/Utils.html#method_getAttributeValues).

**Comment by adaur** [comment]
Thanks!

**Comment by JoshyPHP** [comment]
I edited my previous comment to address the BBcode alias.

**Comment by adaur** [comment]
It is working :)

**Comment by franzliedke** [comment]
Hey friend! :)

Glad you got it working - I would have recommended the same...
