### ISSUE TITLE
<p>&amp;nbsp;</p>

### ISSUE THREAD

**Issue by Brakkar** [s9e/TextFormatter#64]
Hello,

can you please tell me how to manage properly ```&nbsp;``` ?
Right now

```
&nbsp;
```

gets excaped to 

```
&amp;nbsp;
```

which causes ```&nbsp;``` to appear on page.

Also as general best practice, do you suggest to parse text once for all before saving it in db, or when rendering (with caching) ?

**Comment by JoshyPHP** [comment]
That's an HTML entity, you'll need to load the `HTMLEntities` plugin.

Parsing once is the best approach, but it also means you'll need to reparse the text if you want to change some of the configuration. You generally don't have to reparse if all you change is the templates.

**Comment by Brakkar** [comment]
Thanks for support and this incredibly useful plugin.
