### ISSUE TITLE
Problem when resaving converted youtube embed

### ISSUE THREAD

**Issue by Brakkar** [s9e/TextFormatter#65]
Hi,

here is the url I past on a form field that will be saved in the db:

```
https://www.youtube.com/watch?v=PDKKixIWjBM
```

because I have youtube embed, it get saved as:

`<div data-s9e-mediaembed="youtube" style="display:inline-block;width:100%;max-width:640px"><div style="overflow:hidden;position:relative;padding-bottom:56.25%"><iframe allowfullscreen="" scrolling="no" style="background:url(https://i.ytimg.com/vi/PDKKixIWjBM/hqdefault.jpg) 50% 50% / cover;border:0;height:100%;left:0;position:absolute;width:100%" src="https://www.youtube.com/embed/PDKKixIWjBM"></iframe></div></div>`

This does properly display the video.
When I reedit the form, so when the produced content gets parsed by TextForamtter, here is the result:

`<div data-s9e-mediaembed="youtube" style="display:inline-block;width:100%;max-width:640px"><div style="overflow:hidden;position:relative;padding-bottom:56.25%"><iframe allowfullscreen="" scrolling="no" style="background:url(<a href="https://i.ytimg.com/vi/PDKKixIWjBM/hqdefault.jpg">https://i.ytimg.com/vi/PDKKixIWjBM/hqdefault.jpg</a>) 50% 50% / cover;border:0;height:100%;left:0;position:absolute;width:100%" src="<a href="https://www.youtube.com/embed/PDKKixIWjBM%22%3E%3C/iframe%3E%3C/div%3E%3C/div">https://www.youtube.com/embed/PDKKixIWjBM"></iframe></div></div</a>>`

Notice  how the code

`
https://www.youtube.com/embed/PDKKixIWjBM%22%3E%3C/iframe%3E%3C/div%3E%3C/div">https://www.youtube.com/embed/PDKKixIWjBM
`

breaks things up. Could it be a bug ?

here is the config:

```
$configurator = new s9eTextFormatter;
        
        # White liste of html elements
        $configurator->HTMLElements->allowElement( 'p' );
        $configurator->HTMLElements->allowElement( 'u' );
        $configurator->HTMLElements->allowElement( 's' );
        $configurator->HTMLElements->allowElement( 'em' );
        $configurator->HTMLElements->allowElement( 'strong' );
        $configurator->HTMLElements->allowElement( 'li' );
        $configurator->HTMLElements->allowElement( 'ol' );
        $configurator->HTMLElements->allowElement( 'ul' );
        $configurator->HTMLElements->allowElement( 'blockquote' );
        $configurator->HTMLElements->allowElement( 'h1' );
        $configurator->HTMLElements->allowElement( 'h2' );
        $configurator->HTMLElements->allowElement( 'h3' );
        $configurator->HTMLElements->allowElement( 'h3' );
        $configurator->HTMLElements->allowElement( 'h4' );
        $configurator->HTMLElements->allowElement( 'h5' );
        $configurator->HTMLElements->allowElement( 'h6' );
        $configurator->HTMLElements->allowElement( 'pre' );
        $configurator->HTMLElements->allowElement( 'br' );
        
        # Video plugin
        $configurator->plugins->load( 'MediaEmbed' );
        $configurator->MediaEmbed->add( 'dailymotion' );
        $configurator->MediaEmbed->add( 'facebook' );
        $configurator->MediaEmbed->add( 'youtube' );
        $configurator->MediaEmbed->add( 'instagram' );
        $configurator->MediaEmbed->add( 'vimeo' );
        $configurator->MediaEmbed->add( 'vine' );
        $configurator->MediaEmbed->add( 'twitter' );
        
        # Other plugins
        $configurator->Autoemail;
        $configurator->Autolink;
        $configurator->plugins->load( 'HTMLEntities' );
        
        extract( $configurator->finalize() ); # This creates tbe $parser and $renderer variables
        $xml = $parser->parse( $html );
        
        return $renderer->render( $xml );
```

**Comment by JoshyPHP** [comment]
That doesn't look like something the library would be able to produce. Specifically, I don't think there's a way to output this, intentionally or not:

```
src="<a href="https://www.youtube.com/embed/PDKKixIWjBM
```

It looks like something post-processes the output from the library to add those `a` elements. Unless you're able to reproduce this behaviour with a single script, I don't think it's a bug.

**Comment by Brakkar** [comment]
How strange. I double checked:

```
https://www.youtube.com/watch?v=PDKKixIWjBM
```

produces 

`<div data-s9e-mediaembed="youtube" style="display:inline-block;width:100%;max-width:640px"><div style="overflow:hidden;position:relative;padding-bottom:56.25%"><iframe allowfullscreen="" scrolling="no" style="background:url(https://i.ytimg.com/vi/PDKKixIWjBM/hqdefault.jpg) 50% 50% / cover;border:0;height:100%;left:0;position:absolute;width:100%" src="https://www.youtube.com/embed/PDKKixIWjBM"></iframe></div></div>`

When I disable the textformater it produces

```
https://www.youtube.com/watch?v=PDKKixIWjBM
```

Or it could be the orm i'm using (eloquent outside laravel) but i highly doubt it.

**Comment by Brakkar** [comment]
Ok, this might have been caused by browser extension that would change video html to make it downloadable. I disabled the extension, and indeed I don't get the a href code. But still, resaving the outpout generated by your extension, creates something very strange where i can see the entire page in the iframe instead of just the video.

Could you please try saving form with https://www.youtube.com/watch?v=PDKKixIWjBM
, then resave it (it should be the produced code) and confirm everything is normal on your side ?

**Comment by Brakkar** [comment]
Ah, sorry I think it's the iframe that was not allowed, even if I added it in the config later.
Is there no way to have youtube embed without iframe ? I think allowing iframe would be risky.

**Comment by JoshyPHP** [comment]
No, iframes are the only decent way to embed third-party content. What you should do is revert the whole HTML/iframe to the original URL in plain text when editing it.

**Comment by Brakkar** [comment]
Indeed that seems to be a way to resolve the problem. Is there any build in support to reverse process the media embed code ?

**Comment by JoshyPHP** [comment]
There's no built-in support for it, no.
