### ISSUE TITLE
How Can I Add New Video Website ???

### ISSUE THREAD

**Issue by TalhaMoazSarwar** [s9e/TextFormatter#66]
Hello,

I want to add one more website to media embed plugin. How can i embed "Tune.pk" videos ???

Thanks in advance.

**Comment by JoshyPHP** [comment]
I don't know this site specifically but if they allow embedding you'll find a description of the library's API in the docs: http://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/

**Comment by JoshyPHP** [comment]
You can use that as a template and modify it to suit your needs:

```php
$configurator = new s9e\TextFormatter\Configurator;

$configurator->MediaEmbed->add(
    'tunepk',
    [
        'host'    => 'tune.pk',
        'extract' => "!tune\\.pk/video/(?'id'\\d+)!",
        'iframe'  => [
            'width'  => 640,
            'height' => 360,
            'src'    => 'https://tune.pk/player/embed_player.php?vid={@id}&width=640&height=360&autoplay=no'
        ]
    ]
);

// Get an instance of the parser and the renderer
extract($configurator->finalize());

$text = 'https://tune.pk/video/7193514/a-gentleman-2017-official-trailer-1-ft-sidharth-jacqueline';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

echo $html;
```

**Comment by TalhaMoazSarwar** [comment]
Thanks for your quick reply & support.. but i don't know where do i put this code in phpBB...

**Comment by JoshyPHP** [comment]
Then I'm afraid you can't add this site to your forum.

**Comment by TalhaMoazSarwar** [comment]
Ok :-/ Thanks For Your Precious Time...
