### ISSUE TITLE
How to disable/remove Emoji plugin without removing the other plugins

### ISSUE THREAD

**Issue by wulofu** [s9e/TextFormatter#70]
Hello,

How am I able to disable or remove the **Emoji** plugin without removing the other plugins and without disabling the custom emoticons?

I'm having this problem in phpbb 3.2.1.

Thanks for any help you can give

**Comment by JoshyPHP** [comment]
You can simply unload the plugin during configuration with `unset($configurator->Emoji)`. At parsing time you can disable the plugin with `$parser->disablePlugin('Emoji')`. You'll need to do that via an extension.

**Comment by wulofu** [comment]
After almost two hours trying to remove it, I was able to do it by removing Emoji references in files spread throughout the forum file system.

I'm a bit angry for all the work needed to remove a single plugin that shouldn't be made default without giving an option to disable it. Either in ACP or at least some configuration file where you could set a isEnabled to true/false, or comment/uncomment.
I hope someone is able to develop this.

**Comment by JoshyPHP** [comment]
That's something you should ask on a phpBB website, their community forums or in their issue tracker.
