### ISSUE TITLE
Best way to get plain text excerpt from long xml

### ISSUE THREAD

**Issue by beavis** [s9e/TextFormatter#72]
I need to get a plain text excerpt to fill some meta and summary fields, not sure if its better to substr the xml and then parse it or the other way around. What would cause less harm to cutout tags?

Also Im trying to get this excerpt as a plain text representation without any tags, bbcodes or mdown symbols,  get just the content for most tags and replace some rich media tags with emojis (🔗  📹  📷  for URL,MEDIA,IMG etc) kinda like whatsapp notifications do. I guess the text part would be easy on the client just using getText on the desired DOM node but I have to handle it server side.
At this moment I have two configurator sets with different templates for this purpouse and choose one or the other at render time. Since I already have the message parsed I see no point in unparsing it and regexping the substitutions again, but maybe there's an easier approach I'm missing?
Thanks

**Comment by JoshyPHP** [comment]
If what you want is a plain text excerpt then you should use `s9e\TextFormatter\Utils::removeFormatting($xml)`. It will remove most of the formatting (it will leave some standalone text such as emoticons or emoji) and you'll be able to trim it safely afterwards.

If the method leaves some markup that you'd like completely removed you can look running `s9e\TextFormatter\Utils::removeTag($xml, $tagName)` on the original XML before removing the rest of the markup.

**Comment by beavis** [comment]
I have been toying around and the only problem I see with removeFormatting is it keeps the bbcodes of the [media] tag since that pair doesn't get enclosed in \<s\>\</s\> and \<e\>\</e\> (I guess because they are not actually bbcode tags they are managed in other way).
I'm gonna try to replace that xml tag (using a custom replaceTag instead of removeTag) before removeFormatting with an emoji of my choice.
Thanks a lot for the quick response and this superb library :) it made my life way easier.

**Comment by JoshyPHP** [comment]
> it keeps the bbcodes of the [media] tag

To be honest I hadn't thought about it. I'm going to publish an update that correctly identify `[media]` tags as markup. I don't know if that will help your use case because it will not remove the content between the tags, but that seems more correct than the current behaviour.
