### ISSUE TITLE
Litedown: lists and italic 

### ISSUE THREAD

**Issue by beavis** [s9e/TextFormatter#74]
I found another edge case while converting old posts:
```
$configurator = new s9e\TextFormatter\Configurator;
$configurator->Litedown;
extract($configurator->finalize());

$text = "text
* item 1
* item 2
* item 3";

$xml  = $parser->parse($text);
$html = $renderer->render($xml);

echo $html;
```
outputs
```
<p>text
<em> item 1
</em> item 2
* item 3</p>
```
Not sure if markdown spec says lists have to be preceded by newline but all the parsers I have tried render this correctly as a list.

For example same input on github:

text
* item 1
* item 2
* item 3

Is it a bug or working as intended? Thanks

**Comment by JoshyPHP** [comment]
It's working as intended, or at least as expected. Markdown requires a blank line before a list, but [several implementations have chosen not to](https://johnmacfarlane.net/babelmark2/?normalize=1&text=text%0A*+item+1%0A*+item+2%0A*+item+3). The Litedown syntax is largely based on the Markdown syntax, with some liberties taken.

What implementation/library did you use when those posts were created?

**Comment by beavis** [comment]
Our old library is based on [parsedown](http://parsedown.org/) and pecl's bbcode
I run a conversion script that prepares the legacy post for the new parser to fix such incompatibilities before the actual parsing, but this one is a bit tricky to catch

**Comment by JoshyPHP** [comment]
FWIW, I will consider changing the Litedown syntax not to require a blank line before lists because the newer Markdown flavours (such as GitHub's) seem to be moving that way. I definitely appreciate any feedback based on real-world data, e.g. what users actually write and expect.
