### ISSUE TITLE
Update the Litedown syntax to bring it closer to the average Markdown implementation

### ISSUE THREAD

**Issue by JoshyPHP** [s9e/TextFormatter#75]
This issue tracks possible changes to the [Litedown syntax](http://s9etextformatter.readthedocs.io/Plugins/Litedown/Syntax/). Litedown was created a little more than [4 years ago](https://github.com/s9e/TextFormatter/commit/366925a7500065d28346844b5043024caa50c0b8) as an abridged version of the original Markdown. Since then, other flavours with slightly different syntactic rules have appeared or gained popularity, users' expectations have shifted away from the original Markdown and it's time to reevaluate some of the Litedown syntax.

Items of interest:

 - ~~[Should lists always be preceded by a blank line?](https://github.com/s9e/TextFormatter/issues/74)~~ -- **Done** e6f58045de39739c0528fbe19bc9cc7299a3aff2
 - ~~Change the rules for list identations?~~ [[1](https://johnmacfarlane.net/babelmark2/?normalize=1&text=-+a%0A+-+b%0A++-+c)] [[2](https://johnmacfarlane.net/babelmark2/?normalize=1&text=-+a%0A++-+b%0A++++-+c)] -- **No**, let's keep it in line with Markdown for now.
- ~~[Normalize whitespace usage around emphasis marks](https://johnmacfarlane.net/babelmark2/?normalize=1&text=x*+o%0Ax+*o%0Ax*+o%0Ax+*o%0Ax*+o)~~ -- **Done** https://github.com/s9e/TextFormatter/commit/f4be8e77d4bb2710060e80d27edc1ab7603ab244
 - ~~[Consider supporting `super^(script)` for  `super<sup>script</sup>`](https://github.com/s9e/TextFormatter/issues/77)~~ -- **Done** https://github.com/s9e/TextFormatter/commit/92ba7928c7a4d62865dc926a9a81fffaec8e480f
 - ~~[Image size](https://github.com/s9e/TextFormatter/issues/76)~~ -- **Not for now**
 - ???

Cross-posted to [Flarum's community](https://discuss.flarum.org/d/7012-looking-for-feedback-on-the-markdown-syntax).

**Comment by beavis** [comment]
I'm in the process of converting around 30 million posts, other than the issues you already mention I have seen a few edge cases with multi line emphasis like

```
some * text  
more text  
even more * text
```
[babelmark](https://johnmacfarlane.net/babelmark2/?text=some+*+text++%0Amore+text++%0Aeven+more+*+text)

Would commonmark be a good indicator of which way to follow for modern parsers?
Thanks for the great work

**Comment by JoshyPHP** [comment]
Can you provide a couple of real-world examples of an actual text with a false-positive for emphasis? I'd need to know more about the context. Multi-line emphasis is supported by [most Markdown flavours](https://johnmacfarlane.net/babelmark2/?normalize=1&text=x*o%0Ax*o) but implementations differ on details. In most cases it's irrelevant to real-world usage though, that's why I'm interested in what's being used in the wild.

My general strategy is to remain close to what people use on a day-to-day basis. The syntax used on Reddit is slightly different from the one used on GitHub, which is slightly different from the ones used in Slack or Discourse. In practice, however, they are virtually indistinguishable because their differences only appear in edge cases. As such, most actively-maintained implementations such as CommonMark are good on average. Then when it comes to edge cases, the decision is usually a trade-off between code complexity and performance.

**Comment by franzliedke** [comment]
> Would commonmark be a good indicator of which way to follow for modern parsers?

I agree with @beavis. For any tough questions, why not follow their example. They have thought most of these through, and their mission mirrors your intentions (following real-world usage) pretty closely, if I remember it correctly.

**Comment by JoshyPHP** [comment]
You'd have to define what a tough question is. There isn't *a* tough question to solve, there are dozens (arguably hundreds) of small edge cases to handle. Trying to mirror one specific implementation's edge case resolution has a cost in terms of development but no real benefits unless you need strict interoperability. As far as the common usage/core syntax is concerned (IOW what most people use) most implementations already agree.

Here's a concrete example. I'm currently looking into false-positives related to emphasis. The current implementation in Litedown was intentionally kept simple and [does not check for whitespace](https://johnmacfarlane.net/babelmark2/?normalize=1&text=x+*+x+*+x). The next iteration will probably follow rules that are closer or identical to the original Markdown because there's a decent chance that a real person will occasionally want to write something like `a * b = b * a` without it being interpreted as an emphasis. Now, would it be worth spending hours to completely replace the algorithm to support nested emphasis in the form `*x *x* x*`? I don't think it would, for three reasons:

 1. I don't think many users are familiar with the concept of nested emphasis.
 2. I have never seen a CSS stylesheet display nested emphasis differently. Here's how it looks like: *x *x* x*.
 3. CommonMark is the only Markdown flavour that supports nested emphasis; The original Markdown does not support it. None of the PHP libraries michelf/php-markdown, erusev/parsedown or cebe/markdown support it.

It's a feature that is known by few and used by almost(?) no one. That's why I say it would be a waste of a time to try to mirror one specific implementation exactly.
