### ISSUE TITLE
Add class to Pipe Tables table

### ISSUE THREAD

**Issue by VSEphpbb** [s9e/TextFormatter#78]
Can you add a class to the table element created by Pipe Tables?

It would be great to have a way (for a phpBB extension) to use CSS to control some styling, as it is out of the box, totally unstyled and for me the biggest problem with it is a lack of spacing/division between cells, i.e.:

```
LeftCenterRight
x      x      x
```
Would be so nice to have a way to add borders or padding via CSS. Just looking for the `table` is too generic so a class, like `pipe-table` would be excellent.

**Comment by JoshyPHP** [comment]
I prefer to leave the default templates as generic as possible. What you can do is modify the default template after loading the plugin. Here's how I'd do it:

```php
$dom = $configurator->tags['TABLE']->template->asDOM();
foreach ($dom->getElementsByTagName('table') as $table)
{
	$table->setAttribute('class', 'pipe-table');
}
$dom->saveChanges();
```
