### ISSUE TITLE
Adding Brazilian media

### ISSUE THREAD

**Issue by Progresso111** [s9e/TextFormatter#79]
Not sure I am asking this at the right place. PHPBB.com tells me I have to ask here. Anyway.

I would like to ask whether it is possible to add in the  media list five largest Brazilian broadcasters

TV Globo globo.com.br
SBT
TV Record
TV Bandeirantes
TV Manchete

**Comment by JoshyPHP** [comment]
This is the right place to request for a site to be included in this library. However, those sites don't seem like a good fit to be included in the default distribution.

It is possible to add new sites using the [API](https://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/) if you're a programmer or you can find someone to create or modify an extension for it.
