### ISSUE TITLE
mediapack does not put 'rel' attribute in youtube link

### ISSUE THREAD

**Issue by hubaishan** [s9e/TextFormatter#80]
I test this by mediaembded extension for phpBB.
if I put the youtube link with '?rel=0' this attribute does not appear in last rendered iframe src link

**Comment by JoshyPHP** [comment]
That's expected. Only the video ID is extracted from the link, other parameters are ignored. There is no workaround unless you modify the template in PHP via an extension.

**Comment by hubaishan** [comment]
but it gets start time 't'

**Comment by JoshyPHP** [comment]
rel is a presentation attribute that is only relevant to embeds. If you want to change it, you'll have to change the definition yourself.

**Comment by hubaishan** [comment]
Thanks.
