### ISSUE TITLE
Configure a tag as disabled 

### ISSUE THREAD

**Issue by beavis** [s9e/TextFormatter#82]
There's an example on the docs of [disabling a tag before parse time](http://s9etextformatter.readthedocs.io/Getting_started/Runtime_configuration/#toggle-a-tag), well I have the opposite use case: tags that should be disabled by default and only enabled on special cases.

It would be convenient to define them as disabled on config time instead of disabling them on parse time most of the time but I can't find any proper way to do it since `s9e\TextFormatter\Configurator\Items\Tag` lacks the `isDisabled` property, just adding it there and setting `$configurator->tags['NAME']->isDisabled = true;` should do the trick?

**Comment by JoshyPHP** [comment]
I have thought about it in the past and I even have a local branch that does just that for plugins but I never merged it because I don't think it's very useful. The parser should generally be cached rather than rebuilt from scratch every time something is parsed. You can toggle tags and plugins before caching the parser instance and it will become the default state for those tags/plugins.

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addFromRepository('B');
extract($configurator->finalize());

$text = '[b]..[/b]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);
echo "$html\n";

$parser->disableTag('B');
$cache  = serialize($parser);
$parser = unserialize($cache);

$xml  = $parser->parse($text);
$html = $renderer->render($xml);

echo "$html";
```
```html
<b>..</b>
[b]..[/b]
```

Does that make sense to you?

**Comment by beavis** [comment]
Yes, that works as well for my use case. Thanks! 👍

**Comment by beavis** [comment]
I stepped into some unexpected behaviour with disableplugin and mediaembed: disabling the plugin does not work, disabling the MEDIA tag does.

```
$configurator = new s9e\TextFormatter\Configurator;
$configurator->MediaEmbed->add('youtube');
extract($configurator->finalize());

$text = '[media]https://www.youtube.com/watch?v=jNQXAC9IVRw[/media]';

$parser->disablePlugin('MediaEmbed');
echo $parser->parse($text)."\n";

$parser->disableTag('MEDIA');
echo $parser->parse($text)."\n";

$parser->enableTag('MEDIA');
echo $parser->parse($text)."\n";
```
outputs:
```
<r><YOUTUBE id="jNQXAC9IVRw" url="https://www.youtube.com/watch?v=jNQXAC9IVRw"><s>[media]</s>https://www.youtube.com/watch?v=jNQXAC9IVRw<e>[/media]</e></YOUTUBE></r>
<t>[media]https://www.youtube.com/watch?v=jNQXAC9IVRw[/media]</t>
<r><YOUTUBE id="jNQXAC9IVRw" url="https://www.youtube.com/watch?v=jNQXAC9IVRw"><s>[media]</s>https://www.youtube.com/watch?v=jNQXAC9IVRw<e>[/media]</e></YOUTUBE></r>
```
Is this intended?

**Comment by JoshyPHP** [comment]
That's correct. Plugin parsers exist only to handle markup. The only kind of markup that `MediaEmbed` handles is URLs found in plain text, which get assigned to a `MEDIA` tag. `[media]` is a BBCode and its markup is handled by the `BBCodes` plugin.

Similarly, if you disable the `URL` tag it will disable `[url]` from the BBCodes plugin, auto-linked URLs from the `Autolink` plugin and Markdown-like links from the `Litedown` plugin.

**Comment by beavis** [comment]
Alright, thanks
