### ISSUE TITLE
Restrict allowed children in tag

### ISSUE THREAD

**Issue by beavis** [s9e/TextFormatter#83]
According to http://s9etextformatter.readthedocs.io/Internals/API_changes/#0110 since defaultChildRule was removed the default behaviour should be "deny" but in practice looks like it is "allow"

```
$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addFromRepository('B');
$configurator->BBCodes->addFromRepository('I');
$configurator->BBCodes->addCustom(
    '[ONLYB #allowChild=B]{TEXT}[/ONLYB]',
    '<xsl:apply-templates/>'
);

extract($configurator->finalize());

$text = '[onlyb] [b]bold[/b] [i]italic[/i] [/onlyb]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

echo $html;
```
outputs: ``<b>bold</b> <i>italic</i>``

Is there any way to whitelist the allowed childs since that API change? Tried combining ignoreTags with allowChild but as expected it does not work. Thanks

**Comment by JoshyPHP** [comment]
The library uses a set of [rules generators](http://s9etextformatter.readthedocs.io/Rules/Automatic_rules_generation/). One of which, `EnforceContentModels`, enforces the HTML content model(s) by allowing/denying tags where applicable. Here, it will allow basically any other tag since `xsl:apply-templates` is essentially a [no-op](https://en.wikipedia.org/wiki/NOP).

You can remove a specific rules generator or remove them all if you want:

```php
$configurator->rulesGenerator->remove('EnforceContentModels');
$configurator->rulesGenerator->clear();
```

However, if you remove this generator you will have to manually allow each tag everywhere you want it to be allowed. What's your use case for allowing only a single tag in this situation? There are different ways to achieve the equivalent of a whitelist but it depends on what you're trying to do.

**Comment by beavis** [comment]
I'm trying to add an inline element for spoilers/redacted text and allow inside only a subset of inline formatting tags (b,i,u,s) and emojis.

**Comment by JoshyPHP** [comment]
That's interesting. That's not really something that would be solved with a rules generator because they only operate on the templates' content rather than tag names so I think the easiest way would be to keep the default settings and manually deny the tags you don't want in spoilers.

```php
foreach ($configurator->tags as $tagName => $tag)
{
	if (!in_array($tagName, ['B'], true))
	{
		$configurator->tags['ONLYB']->rules->denyChild($tagName);
		$configurator->tags['ONLYB']->rules->denyDescendant($tagName);
	}
}
```

**Comment by beavis** [comment]
That will do for now. Thanks for your support as always

**Comment by beavis** [comment]
Sorry for being a pain in the ass but I think either BlockElementsCloseFormattingElements or BlockElementsFosterFormattingElements generators are preventing this to work.
I want the parent element to be inline, when there is a block child tag it automatically closes the parent tag even if it is not allowed as a child (I'm only allowing inline children to prevent weird behaviours). Oddly seems it only happens when parent has a class defined:

```php
<?php
require 'vendor/autoload.php';

$templates = [
    '<div><xsl:apply-templates/></div>',
    '<span><xsl:apply-templates/></span>',
    '<div class="foo"><xsl:apply-templates/></div>',
    '<span class="foo"><xsl:apply-templates/></span>',
];

foreach ($templates as $tpl) {
    $configurator = new s9e\TextFormatter\Configurator;
    $configurator->BBCodes->addFromRepository('B');
    $configurator->BBCodes->addFromRepository('CENTER');
    $configurator->BBCodes->addFromRepository('I');
    $configurator->BBCodes->addCustom('[SPOILER]{TEXT}[/SPOILER]',$tpl);

    foreach ($configurator->tags as $tagName => $tag)
    {
        if (!in_array($tagName, ['B'], true))
        {
            $configurator->tags['SPOILER']->rules->denyChild($tagName);
            $configurator->tags['SPOILER']->rules->denyDescendant($tagName);
        }
    }

    extract($configurator->finalize());

    $text = '[spoiler]x [b]x[/b] [center]x[/center] [i]x[/i][/spoiler]';
    $xml  = $parser->parse($text);
    $html = $renderer->render($xml);

    echo "$tpl\n$html\n\n";
}
```

Last output is unexpected:
```
<div><xsl:apply-templates/></div>
<div>x <b>x</b> [center]x[/center] [i]x[/i]</div>

<span><xsl:apply-templates/></span>
<span>x <b>x</b> [center]x[/center] [i]x[/i]</span>

<div class="foo"><xsl:apply-templates/></div>
<div class="foo">x <b>x</b> [center]x[/center] [i]x[/i]</div>

<span class="foo"><xsl:apply-templates/></span>
<span class="foo">x <b>x</b></span> <div style="text-align:center"><span class="foo">x</span></div><span class="foo"> [i]x[/i]</span>
```

**Comment by JoshyPHP** [comment]
No worries, it's good to know if there are any issues with the libraries. I don't think there's a workaround in current version so I'll reopen for now and come back to you later.

**Comment by JoshyPHP** [comment]
Alright, I played around with the idea of creating an `ignoreTag` rule but it ended up relatively complicated and it's unclear whether such a rule should apply only to children or to all descendants, so I have decided to drop it for now.

I don't know whether there will ever be a way to ignore specific tags but in the meantime I suggest you use a tag filter that invalidates a tag depending on what other tags are currently open. Here's an example that prepends a tag filter to the `CENTER` tag and invalidates it if any of its ancestors is a `SPOILER` tag.

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->BBCodes->addFromRepository('B');
$configurator->BBCodes->addFromRepository('CENTER');
$configurator->BBCodes->addCustom(
	'[SPOILER]{TEXT}[/SPOILER]',
	'<span class="spoiler"><xsl:apply-templates/></span>'
);

$configurator->tags['CENTER']->filterChain
	->prepend('invalidateInSpoiler')
	->resetParameters()
	->addParameterByName('openTags');

function invalidateInSpoiler($openTags)
{
	foreach ($openTags as $tag)
	{
		if ($tag->getName() === 'SPOILER')
		{
			return false;
		}
	}

	return true;
}

extract($configurator->finalize());

$text = '[spoiler][b]x[/b] [center]x[/center][/spoiler]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<span class="spoiler"><b>x</b> [center]x[/center]</span>
```

References:

 * http://s9etextformatter.readthedocs.io/Filters/Tag_filters/
 * http://s9etextformatter.readthedocs.io/Filters/Callback_signature/
