### ISSUE TITLE
RegexpBuilder::fromList() is inefficient

### ISSUE THREAD

**Issue by nunoplopes** [s9e/TextFormatter#84]
TextFormatter is used by phpBB 3.2 to replace stop words.  My forum just exposed an inefficiency in RegexpBuilder, which makes PHP consume > 16 GB of RAM.
The input to fromList():

```
array (
  0 => 'merda',
  1 => 'fodasse',
  2 => 'pk?',
  3 => 'pk',
  4 => 'fodido',
  5 => 'fudido',
  6 => 'cu',
  7 => 'cona',
  8 => 'CARALHO',
  9 => 'CONA',
  10 => 'CU',
  11 => 'caralho',
  12 => 'mod',
  13 => 'bófia',
  14 => 'nina',
  15 => 'nino',
  16 => 'foda-se',
  17 => 'tb',
  18 => 'PUTA',
  19 => 'puta',
  20 => 'MERDA',
  21 => 'CABRÃO',
  22 => 'cabrão',
  23 => 'cabrões',
  24 => 'CABRÕES',
  25 => 'peida',
  26 => 'PEIDA',
)
```
In case-insensitive mode, I would expect the following output from this function:
`(?>merda|fodasse|pk[?]?|f[ou]dido|cu|cona|caralho|nin[ao]|puta|peida|cabr[ãÃ]o|cabr[õÕ]es|tb|foda-se|mod|bófia)`

Cross bug report for phpBB: https://tracker.phpbb.com/browse/PHPBB3-15465

**Comment by JoshyPHP** [comment]
What version of PHP is that?

**Comment by nunoplopes** [comment]
All I've tried. 5.6 crashed right away. 7.0 run out of memory (16 GB) after 1 minute.

**Comment by JoshyPHP** [comment]
The issue is an infinite recursion caused by the strings `pk` and `pk?`. The master branch has been patched to avoid it.

**Comment by nunoplopes** [comment]
works great, thank you!
