### ISSUE TITLE
RegexpBuilder does not do case-insensitive correctly for UTF-8

### ISSUE THREAD

**Issue by brunoais** [s9e/TextFormatter#85]
https://github.com/s9e/TextFormatter/blob/master/src/Configurator/Helpers/RegexpBuilder.php#L48
Does not make the comparison case-insensitive for characters like "Àáaã", etc...
Use [`mb-strtolower()`](http://php.net/manual/en/function.mb-strtolower.php) instead.

**Comment by JoshyPHP** [comment]
Case folding is more complicated than normalizing to lowercase. It works well enough with ASCII characters in Normalization Form C but it can cause issues with some locales. This is also why this method uses `strtr()` and not `strtolower()`. See https://www.w3.org/International/wiki/Case_folding for reference.

Case sensitivity is handled in PCRE; This flag is only used to produce smaller regexps where possible without sacrificing correctness.
