### ISSUE TITLE
BBCode tag with content starting with : gets ignored when using Litedown

### ISSUE THREAD

**Issue by beavis** [s9e/TextFormatter#86]
Due to tag priority (I guess) whenever you use `[TAG]:whatever[/TAG]` the tag gets ignored because of litedown LinkReferences. This gets tricky when having aliases using :code: like emojis for example `[quote]:+1:[/quote]` displays nothing.

**Comment by beavis** [comment]
I could just increase priority of litedown reference from -2 to 1 but not really sure of the collateral damage of this change, seems it breaks one test

**Comment by JoshyPHP** [comment]
I have updated the regular expression used to match link references to be more strict in what's accepted. It should eliminate most of those issues and make it hard for a BBCode to be accepted as a link reference. However, there are still edge cases that are particularly difficult to solve. Feel free to reopen this issue if you encounter one.

**Comment by beavis** [comment]
Much appreciated, thank you
