### ISSUE TITLE
Unescaped text inside ignored tag triggers XML warning

### ISSUE THREAD

**Issue by beavis** [s9e/TextFormatter#87]
I found some warnings when using a custom bbcode tag with unexpected content (which gets ignored), the resulting XML was raising `Warning: DOMDocument::loadXML(): EntityRef: expecting ';' in Entity` due to ampersands not being scaped inside ignore tags
I think the culprit is [this line](https://github.com/s9e/TextFormatter/blob/83cb8e43212751231c6010238947cbbc77d8c210/src/Parser.php#L616)

```
// If the catchup text is not entirely composed of whitespace, we put it inside ignore
// tags
if (strspn($catchupText, " \n\t") < $catchupLen)
{
	$catchupText = '<i>' . $catchupText . '</i>';
}
```
should it be replaced with the following code?
```
// If the catchup text is not entirely composed of whitespace, we put it inside ignore
// tags
if (strspn($catchupText, " \n\t") < $catchupLen)
{
	$catchupText = '<i>' . htmlspecialchars($catchupText, ENT_NOQUOTES, 'UTF-8') . '</i>';
}
```
Is it ok to submit pull requests?
Thanks

**Comment by JoshyPHP** [comment]
Thanks for the report, I'm going to fix it right away and review the entire method for similar defects.

**Comment by JoshyPHP** [comment]
I've just pushed a fix. It it fixes your issues and all tests pass, I'll publish a release shortly after.

**Comment by beavis** [comment]
Issues are gone after the fix, thanks for the quick response
