### ISSUE TITLE
Media Embed AMazon Not Working

### ISSUE THREAD

**Issue by VSEphpbb** [s9e/TextFormatter#88]
Amazon does not seem to be working. I just get a blank iframe area when attempting to use it. Using 0.13.1

Also this: https://www.phpbb.com/customise/db/extension/mediaembed/support/topic/188351

Thanks.

**Comment by JoshyPHP** [comment]
My money is on your adblocker. Firefox's privacy blocker thing does that, too.

**Comment by VSEphpbb** [comment]
Yep, for me it was adblocker. Not sure about the issue posted at phpbb.com though.

**Comment by JoshyPHP** [comment]
Try to reproduce it on a default install, chances are it's working fine.

In addition, I've looked at the site definition but I couldn't find any version of it that used `&ref=` in a URL, nor do I know what "embedded book/movies previews" refer to. That looks like a different extension.
