### ISSUE TITLE
imgur link parser error.

### ISSUE THREAD

**Issue by wliu6v** [s9e/TextFormatter#89]
There's two different imgur link: 
- https://imgur.com/j54iW
- https://imgur.com/gallery/j54iW

But they are resolved into the same card.

![image](https://user-images.githubusercontent.com/5987831/35838203-32b7de90-0b25-11e8-96b7-f3e661c67da6.png)

These imgur id are different:

![image](https://user-images.githubusercontent.com/5987831/35838248-5e709568-0b25-11e8-84fd-fda39ea89f6c.png)

**Comment by JoshyPHP** [comment]
Yes, links with an ID shorter than 6 characters are interpreted as gallery links because of some backward compatibility issue.

I'm not sure I can change that behaviour so currently, the only workaround is to link to the image directly, e.g. `https://i.imgur.com/j54iW.jpg`

**Comment by wliu6v** [comment]
I'm working on amp, and using `<amp-imgur>` to implement imgur card. 
For amp-imgur, these two imgur are correct with different imgur id : `j54iW` and `a/j54iW`.

![image](https://user-images.githubusercontent.com/5987831/35849193-bd3cf8a8-0b5b-11e8-8626-df5404b82a56.png)

--

![image](https://user-images.githubusercontent.com/5987831/35849203-c35de5b2-0b5b-11e8-8c96-61a0e8cbd4d1.png)

--

I‘m not sure if you can fix this issue in a similar way.
