### ISSUE TITLE
PipeTable responsive design

### ISSUE THREAD

**Issue by DogSports** [s9e/TextFormatter#92]
It's possible to add an attribute `data-label` in `<td>` for responsive design phone/tablet with CSS ?

Exemple: https://codepen.io/AllThingsSmitty/pen/MyqmdM

Thanks

**Comment by JoshyPHP** [comment]
I'll think about it but I don't think that's something I will add in the foreseeable future. There are many ways to implement this kind of attributes, each with its own set of trade-offs. The value for the label could be stored in an attribute at parsing time using PHP, created at rendering time using XSLT or even added on the client side using JavaScript.

Here's an example that uses XSLT:

```php
$configurator = new s9e\TextFormatter\Configurator;
$configurator->PipeTables;

$dom = $configurator->tags['TD']->template->asDOM();
$dom->getElementsByTagName('td')->item(0)->setAttribute(
	'data-label',
	'{../../../THEAD/TR/TH[1 + count(current()/preceding-sibling::TD)]}'
);
$dom->saveChanges();

extract($configurator->finalize());

$text = "a|b\n"
      . "-|-\n"
      . "c|d\n";
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<table><thead><tr><th>a</th><th>b</th></tr></thead>
<tbody><tr><td data-label="a">c</td><td data-label="b">d</td></tr></tbody></table>
```

**Comment by JoshyPHP** [comment]
I thought about it and decided to hold off adding anything unless there's a clear need for it in the library. I'll keep an eye on your extension at https://discuss.flarum.org/d/9719-markdown-tables to see how your current solution works out.

**Comment by DogSports** [comment]
Thank you for taking the time to think about it and your answer.

I opted for Javascipt:

```
this.$('.Post-body table thead th').each(function () {
    this.$('.Post-body table tbody td:nth-child(' + ($(this).index() + 1) + ')').attr('data-th', $(this).html())
})
```

But this code is not satisfactory if there are several tables on the same page.

**Comment by JoshyPHP** [comment]
I think the XSLT solution is the most adequate as it's the simplest but if I had to use JavaScript I'd use something like that:

```js
function addDataLabelsToTable(table)
{
	let labels = [];
	for (let th of table.getElementsByTagName('th'))
	{
		labels.push(th.textContent);
	}
	for (let tr of table.getElementsByTagName('tr'))
	{
		let i = -1;
		for (let td of tr.getElementsByTagName('td'))
		{
			td.setAttribute('data-label', labels[++i] || '');
		}
	}
}
for (let table of document.getElementsByTagName('table'))
{
	addDataLabelsToTable(table);
}
```

With that sort of template:
```xsl
<td data-s9e-livepreview-postprocess="addDataLabelsToTable(this)" data-s9e-livepreview-ignore-attrs="data-label"><xsl:apply-templates/></td>
```

**Comment by DogSports** [comment]
I do not master XSLT, let alone with Flarum. Your Javascript code works! Thank you
