### ISSUE TITLE
MediaEmbed: direct link

### ISSUE THREAD

**Issue by nerestaren** [s9e/TextFormatter#95]
Hi, we're using (a modified version of the) phpBB extension.

I would like to further modify it to support direct links. For example, a user added a link to ptpb.pw and expected that it would work with the [media] bbcode.

Is there a way to match *.mp4, *.webm and display <video> and similar for <audio> and <img>?

Thank you!

**Comment by JoshyPHP** [comment]
Not with the MediaEmbed plugin. You can convert links with the Autovideo plugin without using BBCodes: https://s9etextformatter.readthedocs.io/Plugins/Autovideo/Synopsis/

**Comment by nerestaren** [comment]
Oops. Without using backticks my third paragraph didn't make any sense!

I meant this:

> Is there a way to match *.mp4, *.webm and display `<video>` and similar for `<audio>` and `<img>`?

So, I do not want to convert links magically or whatever. I want to use `[media]http://a-link-to-a-video.mp4[/media]` and get `<video src="http://a-link-to-a-video.mp4"></video>`.

And I'm sorry if this is not the channel you are supposed to ask for support!

Thank you!
