### ISSUE TITLE
Mediaembed no longer able to parse videos from vk.com?

### ISSUE THREAD

**Issue by kastashov** [s9e/TextFormatter#96]
Looks like videos from vk.com cannot be embedded any longer, even those that worked previously (a few months ago).
E. g. https://vk.com/video-76669927_456245937
or https://vk.com/video-140033084_456239051
From the looks of it, it's no longer possible to get the "hash" param from vk?

**Comment by JoshyPHP** [comment]
VK changed their code a few days ago and the library was updated accordingly. A new release will be available in the next few days or if you don't want to wait you can try a live snapshot by switching to a [release branch](https://github.com/s9e/TextFormatter/branches).

Below is what the output from the current master branch:

```php
$configurator = new s9e\TextFormatter\Configurator;

$configurator->MediaEmbed->add('vk');

extract($configurator->finalize());

$text = 'https://vk.com/video-76669927_456245937';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$xml\n");
```
```xml
<r><VK hash="ee1d823d24b74a1f" oid="-76669927" vid="456245937">https://vk.com/video-76669927_456245937</VK></r>
```
