### ISSUE TITLE
Support for ZetaBoards flavour of BBCode

### ISSUE THREAD

**Issue by davidferguson** [s9e/TextFormatter#97]
I'm migrating my forum over from [ZetaBoards](http://www.zetaboards.com/) (a free forum host), to phpBB, however while most of the BBCode is compatible, there are a few differences that would be great to be fixed (I'm not familiar with phpBB's or TextFormatter's codebase, so any pointers to how these can be implemented would be useful).

----
### Unnamed Tag Attributes
Rather than using named attributes like:
``[border color=red width=2 style=solid]text[/border]``, ZetaBoards unnamed attributes: ``[border=red,2,solid]text[/border]``, with the width and style parameters optional, but style only being applicable when width is specified, ie, all of the following are valid:

``[border=red]text[/border]``
``[border=red,2]text[/border]``
``[border=red,2,solid]text[/border]``

but ``[border=red,solid]text[/border]`` is not valid

This is the similar for quote tags, with are written as: ``[quote=author,(time=timestamp)]quoted text[/quote]`` with both the author and the timestamp optional, ie, all of the following are valid:

``[quote]quoted text[/quote]``
``[quote=author]quoted text[/quote]``
``[quote=(time=timestamp)]quoted text[/quote]``

Where timestamp is in Unix Epoch format.

----
### Tables
ZetaBoards also has a different way of writing `[table]`s, as shown below:

``[table=2,Table Title]Column 1, Row 1[c]Column 2, Row 1[c]Column 1, Row 2[c]Column 2, Row 2[/table]``

Table Title is optional, and `2` attribute in the `[table]` tag specifies the number of rows of the table. The `[c]` tag denotes a new cell starting. Tables can also contain whitespace, which is ignored. See [this post](http://support.zathyus.com/single/?p=8137194&t=5046122) for examples of table syntax, including nested tables.

----
And those are the main differences. There are also a few new tags, but they can all be implemented easily using the [Custom BBCode Syntax](https://s9etextformatter.readthedocs.io/Plugins/BBCodes/Custom_BBCode_syntax/). It's really just the unnamed attributes and tables that I'm having difficulty with.

(For reference, I beleive [this page](http://w11.zetaboards.com/Something_Different/pages/bbcode/) lists all the ZetaBoards BBCode, except for tables. The [official ZetaBoards BBCode List](http://support.zathyus.com/keys/?c=1) appears to be rather out of date, missing tags like `[table]`, `[member]`,`[staff]`,`[note]`)

**Comment by JoshyPHP** [comment]
I don't intend to support ZetaBoards's BBCodes specifically but if you're motivated you can create a phpBB extension that adds a compatibility layer for it. The example below shows how to handle the custom `[border]` and `[quote]` BBCodes, and a generic `[table]` BBCode. The row splitter is more complicated to implement but it's not impossible. It would have been easier if the BBCode specified the number of columns rather than the number of rows.

```php
$configurator = new s9e\TextFormatter\Configurator;

// Default phpBB quote BBCode, not required in the extension
$configurator->BBCodes->addCustom(
	"[QUOTE
		author={TEXT1;optional}
		post_id={UINT;optional}
		post_url={URL;optional;postFilter=#false}
		profile_url={URL;optional;postFilter=#false}
		time={UINT;optional}
		url={URL;optional}
		user_id={UINT;optional}
		author={PARSE=/^\\[url=(?'url'.*?)](?'author'.*)\\[\\/url]$/i}
		author={PARSE=/^\\[url](?'author'(?'url'.*?))\\[\\/url]$/i}
		author={PARSE=/(?'url'https?:\\/\\/[^[\\]]+)/i}
	]{TEXT2}[/QUOTE]",
	'author:<xsl:value-of select="@author"/> time:<xsl:value-of select="@time"/>'
);

// ====== Extension code starts here ======
$configurator->BBCodes->addCustom(
	'[border={COLOR},{INT},{ALNUM} color={COLOR} width={INT} style={ALNUM}]{TEXT}[/border]',
	'<div style="border:{@style} {@width}px {@color}">{TEXT}</div>'
);
$configurator->BBCodes->addCustom(
	'[table={INT},{TEXT} rows={INT?} title={TEXT?} #createChild=TR]{TEXT2}[/table]',
	'<table>{TEXT2}</table>'
);
$configurator->BBCodes->addCustom(
	'[tr #createChild=TD]{TEXT}[/tr]',
	'<tr>{TEXT}</tr>'
);
$configurator->BBCodes->addCustom(
	'[td]{TEXT}[/td]',
	'<td>{TEXT}</td>'
);

// Create [c] as an alias to [td]
$configurator->BBCodes->add('c')->tagName = 'TD';

// Interpret [quote=foo,123] as [quote author=foo time=123]
$configurator->tags['quote']->attributePreprocessors
	->add('author', '/^(?<author>.+),\\(time=(?<time>\\d+)\\)$/');
// ====== Extension code ends here ======

extract($configurator->finalize());

$text = "[border color=red width=2 style=solid]text[/border]\n"
      . "[border=red,2,solid]text[/border]\n"
      . "[quote]quoted text[/quote]\n"
      . "[quote=author]quoted text[/quote]\n"
      . "[quote=author,(time=123)]quoted text[/quote]\n"
      . '[table=2,Table Title]Column 1, Row 1[c]Column 2, Row 1[c]Column 1, Row 2[c]Column 2, Row 2[/table]';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```
```html
<div style="border:solid 2px red">text</div>
<div style="border:solid 2px red">text</div>
author: time:
author:author time:
author:author time:123
<table><tr><td>Column 1, Row 1</td><td>Column 2, Row 1</td><td>Column 1, Row 2</td><td>Column 2, Row 2</td></tr></table>
```
