### ISSUE TITLE
Re-add Twemoji

### ISSUE THREAD

**Issue by tobscure** [s9e/TextFormatter#99]
🙅‍♂️ EmojiOne 3.1's licensing is more restrictive than it used to be. You no longer get vector versions and it requires pretty strict attribution on every page where emojis are used. https://www.emojione.com/licenses/free

🎉 Twemoji have just released a new version compatible with Unicode 11.0. It remains CC-BY 4.0 and their requirements for attribution are much more lax. https://twemoji.twitter.com

🤔 Can we please either get Twemoji added back in as an option, or just make it the default and drop EmojiOne altogether?

**Comment by JoshyPHP** [comment]
Yes, but not easily. Some time ago, EmojiOne and Twemoji have started diverging in their filename scheme. EmojiOne only contains the relevant emoji codepoints while Twemoji contains Zero Width Joiner codepoints and Variation Selectors 16, but only in the middle of the sequences, never at the end.

I posted something about it [on phpBB.com](http://area51.phpbb.com/phpBB/viewtopic.php?p=311111#p311111):

```
Each emoji set uses a different filename scheme, which makes it much harder to switch from a one to another unless you maintain your own fork.

* EmojiOne: [1f3f3-1f308.png](https://github.com/emojione/emojione-assets/blob/master/png/128/1f3f3-1f308.png)
* Twemoji: [1f3f3-fe0f-200d-1f308.svg](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f3f3-fe0f-200d-1f308.svg)
* Noto: [emoji_u1f3f3_200d_1f308.svg](https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f3f3_200d_1f308.svg)

Currently, the value that's stored in the post's data is **1f3f3-1f308**. There's no easy way to convert that into the other sets' filenames.
```

So what you need is an image set with a filename scheme that's compatible with EmojiOne's. For reference, I current maintain an experimental fork of Twemoji and Noto to evaluate how much work it takes. You can find it at https://github.com/s9e/emoji-assets but have no long term plan and I can't say how long I'll keep it up to date.

**Comment by tobscure** [comment]
Hmm, interesting. I don't really understand how unicode works, but the complexity here makes me think in Flarum's case that we should consider going back to [the way we used to do it](https://discuss.flarum.org/d/271-text-formatting-in-flarum/40) – store the actual unicode in the database, and make the client-side responsible for running Twemoji (or another transformation library) if desired.

The emoji autocomplete would also be purely client-side, inputting a unicode character when you select an emoji name, just like on GitHub 👍

Do you have any thoughts on this approach?

**Comment by JoshyPHP** [comment]
It's not really related to Unicode, it's about mapping text to a filename. Every emoji set out there have gone their own incompatible way to do that apparently.

I generally don't like client-side libraries for emoji. You could do the same thing in PHP if you want something dynamic.

GitHub's emoji selector doesn't use emoji characters (e.g. `👍`), it uses its own ASCII aliases such as `:+1:`. Unfortunately there's no standard for ASCII aliases. The latest version of EmojiOne has something they call "[alpha codes](https://github.com/emojione/emojione/tree/master/extras/alpha-codes)" which they currently license under MIT.

**Comment by tobscure** [comment]
But on GitHub, if you type `:+1` and press Enter, the unicode character 👍 is inserted into the textarea, and that gets posted to the server without any ASCII alias involved. So the ASCII aliasing is purely a client-side thing, and wouldn't even be TextFormatter-related.

Anyway, I think this is more Flarum-specific and not related to the original issue any longer, so I'll close this :)

**Comment by JoshyPHP** [comment]
That's not what it does for me on Chromium. It always inserts the ASCII alias and never the Unicode emoji.

**Comment by JoshyPHP** [comment]
Starting with the soon-to-be-unreleased 1.3.0, Emoji tags provide an attribute named `tseq` that contains the basename for Twemoji asset files.

https://s9etextformatter.readthedocs.io/Plugins/Emoji/Synopsis/#using-twemoji
